# Act 1: corridor, checkpoint, medical deck.

IONA_MEET = {
    "id": "iona_meet",
    "entry": [{"node": "start"}],
    "nodes": {
        "start": N("iona", "Pickets down. You fight like Lattice: you watch the room before you watch the target. Officer Iona Rell, ship's security. Who are you?",
            C("{name}. Former operator. Right now, a passenger.", "who_plain"),
            C("Lattice Corps, operator first class. Discharged.", "who_vet", cond=[{"background": "veteran"}], tag="Veteran", effects=[inf("iona", 2, "meet_vet", "Gave her a straight service record")]),
            C("Does it matter? You're alive.", "who_hard", tone="hard", effects=[inf("iona", -1, "meet_dodge", "Dodged her question")])),
        "who_plain": N("iona", "A passenger with a Lumen Edge. All right, passenger. Here's the situation.", nxt="situation"),
        "who_vet": N("iona", "First class. Then you know how a lattice goes wrong. Here's the situation.", nxt="situation"),
        "who_hard": N("iona", "It matters to my report, if anyone ever reads it. Fine. Here's the situation.", nxt="situation"),
        "situation": N("iona", "The WARDEN went to Archive Protection twenty minutes ago. The commander set its priorities before we left orbit: archive first, command second, crew third. Passengers didn't make the list. Lantern reclaimers cut in through the dorsal hull over the hold. Launch craft Petrel is in Bay 2, all the way forward: checkpoint, medical, engineering, archive hold, command, bay.",
            C("Then we go forward and we bring everyone we can on the way.", "r_comp", tone="compassionate", effects=[inf("iona", 5, "meet_everyone", "Wants to bring everyone"), align(3, "meet_everyone", "Resolved to save everyone they can")]),
            C("We move fast. We can't stop for every door.", "r_prag", tone="pragmatic", effects=[inf("iona", 1, "meet_fast", "Kept a clear head")]),
            C("I'm getting on that craft. You can come with me.", "r_self", tone="self-interested", effects=[inf("iona", -3, "meet_self", "Only thinking of themself")]),
            C("Why would anyone set a ship to guard cargo over people?", "r_skep", tone="skeptical", effects=[inf("iona", 2, "meet_why", "Questioned the commander's priorities")]),
            C("Follow my lead and we both live.", "r_hard", tone="hard", effects=[inf("iona", -2, "meet_orders", "Tried to give her orders")])),
        "r_comp": N("iona", "Everyone we can. That's the job, isn't it. That's the only version of the job I can live with.", nxt="medpac"),
        "r_prag": N("iona", "Fast saves people too. Fine. But I'll stop for the ones who can't run.", nxt="medpac"),
        "r_self": N("iona", "Generous. I'm not leaving my post just to buy you a seat, but our routes match. For now.", nxt="medpac"),
        "r_hard": N("iona", "I don't take orders from passengers. I'll take good ideas. You've had one so far: shooting the drones.", nxt="medpac"),
        "r_skep": N("iona", "Because the commander says what's in that hold matters more than all of us. Maybe it does. She also had me seal the passenger ward on the medical deck two hours ago, with five people inside. I did it. I'm telling you because you're going to see that door.", nxt="medpac", effects=[flag("iona_told_ward")]),
        "medpac": N("iona", "Here. Field medpac. Use it, don't hoard it. It takes a moment to apply, so you can't slap three on in one breath, and nobody can. And take my keycard. The armory locker at the checkpoint is mechanical; the WARDEN can't lock that one.",
            effects=[{"give_item": "medpac", "count": 1, "key": "iona_medpac"}, {"give_item": "iona_keycard", "count": 1, "key": "iona_keycard"}, {"tutorial": "healing"}, {"tutorial": "queue"}],
            *[C("Thanks, Iona. Let's move.", "end_node"),
              C("You're trusting a stranger with your keycard?", "trust")]),
        "trust": N("iona", "I'm trusting the stranger who just saved my life. Don't make me revise that.", nxt="end_node", effects=[inf("iona", 1, "meet_trust", "Asked why she trusted them")]),
        "end_node": N("iona", "Checkpoint's through that door. WARDEN put a turret and pickets on it. I'd rather not walk into its guns, if you have a better idea.", effects=[xp(100, "iona_meet", "Joined forces with Iona Rell")], end=True),
    },
}

CHK_TERMINAL = {
    "id": "checkpoint_terminal",
    "names": {"terminal": "Checkpoint Terminal"},
    "entry": [{"node": "start"}],
    "nodes": {
        "start": N("system", "CHECKPOINT SECURITY — WARDEN SUBNET 3. Guest session. Operator: {name}... (the acting character is shown on each option).",
            C("Review the camera logs.", "logs"),
            C("Take the point-defense turret offline.", "turret_ok", cond=[{"not": {"flag": "turret_disabled"}}, {"not": {"flag": "checkpoint_clear"}}],
              check=chk("computer_use", 13, "chk_turret", who="actor"), success="turret_ok", failure="turret_fail",
              success_effects=[flag("turret_disabled"), {"enemy": "chk_turret", "set": {"hostile_override": "offline"}}, xp(50, "chk_turret_off", "Took the checkpoint turret offline")],
              failure_effects=[{"start_encounter": "enc_checkpoint"}, flag("checkpoint_alarm")]),
            C("Override the forward blast door.", "door_ok", cond=[{"not": {"flag": "checkpoint_solved"}}],
              check=chk("computer_use", 15, "chk_door", who="actor"), success="door_ok", failure="door_fail",
              success_effects=[{"world": "d_blast", "set": {"locked": False, "open": True}}, flag("checkpoint_solved"), flag("checkpoint_by", "terminal"), xp(60, "checkpoint_door", "Opened the forward blast door")],
              failure_effects=[{"start_encounter": "enc_checkpoint"}, flag("checkpoint_alarm")]),
            C("Order the picket drones back to their charging cradles.", "drones_ok", cond=[{"not": {"flag": "drones_recalled"}}, {"not": {"flag": "checkpoint_clear"}}],
              check=chk("computer_use", 17, "chk_drones", who="actor"), success="drones_ok", failure="drones_fail",
              success_effects=[flag("drones_recalled"), {"enemy": "chk_d1", "set": {"hostile_override": "offline"}}, {"enemy": "chk_d2", "set": {"hostile_override": "offline"}}, xp(50, "chk_drones", "Recalled the checkpoint drones")],
              failure_effects=[{"start_encounter": "enc_checkpoint"}, flag("checkpoint_alarm")]),
            C("Authenticate with your neural signature.", "cred", tag="Resonance credential", cond=[{"controlled": "player"}, {"not": {"flag": "checkpoint_solved"}}]),
            C("Log off.", end=True)),
        "logs": N("system", "Camera logs cycle across the screen: reclaimer pods latching onto the dorsal hull, turrets waking, Commander Varr sealing herself in, and Officer Rell's hand resting on the Ward 2 panel for eleven seconds.", nxt="start", effects=[{"codex": "cx_camera_logs"}]),
        "turret_ok": N("system", "POINT DEFENSE 3-A: MAINTENANCE MODE. The turret's barrels droop toward the deck.", nxt="after_turret"),
        "after_turret": R(([{"flag": "drones_recalled"}], "all_quiet"), ([], "start")),
        "turret_fail": N("system", "INTRUSION DETECTED. SESSION TERMINATED. The checkpoint lights snap to red and the turret swings toward you.", end=True),
        "door_ok": N("system", "FORWARD BLAST DOOR: OVERRIDE ACCEPTED. The door to the medical deck rumbles open.", nxt="start"),
        "door_fail": N("system", "OVERRIDE REJECTED. SECURITY ALERT. Something in the room starts moving.", end=True),
        "drones_ok": N("system", "PICKETS 3-1, 3-2: RETURN TO CRADLE. The drones drift to the wall and power down.", nxt="after_drones"),
        "after_drones": R(([{"flag": "turret_disabled"}], "all_quiet"), ([], "start")),
        "all_quiet": N("system", "CHECKPOINT 3: ALL UNITS INACTIVE.", effects=[{"resolve_encounter": "enc_checkpoint", "resolution": "technical"}], nxt="start"),
        "drones_fail": N("system", "COMMAND REJECTED: GUEST PRIVILEGES. SECURITY ALERT.", end=True),
        "cred": N("narrator", "You lay your palm on the reader and feel the old hum answer: a cold, familiar attention brushing the back of your skull.", nxt="cred2"),
        "cred2": N("warden", "CUSTODIAN AUTHORITY ACCEPTED. CHECKPOINT 3: STAND DOWN. FORWARD ACCESS GRANTED. WELCOME BACK.",
            effects=[{"world": "d_blast", "set": {"locked": False, "open": True}}, flag("checkpoint_solved"), flag("checkpoint_by", "credential"), flag("used_credential"), flag("warden_tracking"),
                     {"inc_flag": "credential_uses", "key": "cred_terminal"}, {"codex": "cx_credential"}, {"resolve_encounter": "enc_checkpoint", "resolution": "credential"},
                     xp(60, "checkpoint_door", "Opened the forward blast door")],
            nxt="cred_react"),
        "cred_react": R((IONA, "iona_react"), ([], "end_node")),
        "iona_react": N("iona", "'Welcome back.' The ship knows you. That system is shooting passengers in the halls and it just opened a door for you. Explain that.",
            C("I don't know. It shouldn't. I'm going to find out why.", "honest", effects=[inf("iona", 2, "cred_honest", "Answered honestly about the credential")]),
            C("Something from the Lattice program. I'll tell you when I understand it.", "honest2", effects=[inf("iona", 1, "cred_later", "Promised to explain the credential")]),
            C("Does it matter? The door's open.", "dismiss", tone="hard", effects=[inf("iona", -3, "cred_dismiss", "Brushed off the credential")])),
        "honest": N("iona", "Then we find out together. And if that thing starts calling you 'commander', I'm going to have questions.", nxt="end_node"),
        "honest2": N("iona", "Hold me to that.", nxt="end_node"),
        "dismiss": N("iona", "It matters to the people it isn't opening doors for.", nxt="end_node"),
        "end_node": N("system", "The checkpoint falls silent.", end=True),
    },
}

CHK_CRED = {
    "id": "checkpoint_credential",
    "entry": [{"node": "start"}],
    "nodes": {
        "start": N("narrator", "You press your palm to the blast door scanner. The hum at the back of your skull answers it like a tuning fork.", nxt="w"),
        "w": N("warden", "CUSTODIAN AUTHORITY ACCEPTED. CHECKPOINT 3: STAND DOWN. FORWARD ACCESS GRANTED. WELCOME BACK.",
            effects=[{"world": "d_blast", "set": {"locked": False, "open": True}}, flag("checkpoint_solved"), flag("checkpoint_by", "credential"), flag("used_credential"), flag("warden_tracking"),
                     {"inc_flag": "credential_uses", "key": "cred_door"}, {"codex": "cx_credential"}, {"resolve_encounter": "enc_checkpoint", "resolution": "credential"},
                     xp(60, "checkpoint_door", "Opened the forward blast door")],
            nxt="react"),
        "react": R((IONA, "iona"), ([], "done")),
        "iona": N("iona", "Welcome back? It knows you. Want to explain that?",
            C("I don't know. It shouldn't. I'm going to find out why.", "a", effects=[inf("iona", 2, "cred_honest", "Answered honestly about the credential")]),
            C("Later. When I understand it.", "b", effects=[inf("iona", 1, "cred_later", "Promised to explain the credential")]),
            C("Does it matter? The door's open.", "c", tone="hard", effects=[inf("iona", -3, "cred_dismiss", "Brushed off the credential")])),
        "a": N("iona", "Then we find out together.", nxt="done"),
        "b": N("iona", "Hold me to that.", nxt="done"),
        "c": N("iona", "It matters to the people it isn't opening doors for.", nxt="done"),
        "done": N("system", "The turret's barrels sag. The pickets drift to their cradles.", end=True),
    },
}

TAV_MEET = {
    "id": "tav7_meet",
    "entry": [{"node": "start"}],
    "nodes": {
        "start": N("tav7", "Patterns persisting: mine, theirs, yours. Thank you. I am Tav-7, maintenance, the seventh of my line. I have been standing between the cutters and Dr. Varga's patients because nobody else was assigned to.",
            C("Thank you for protecting them.", "thanks", tone="compassionate", effects=[inf("tav7", 3, "meet_thanks", "Thanked them for protecting patients")]),
            C("You're a maintenance unit. Why aren't you obeying the WARDEN like the rest?", "why", tone="skeptical", effects=[inf("tav7", 2, "meet_why", "Was curious about them as a person")]),
            C("I spent years cutting up ships like this. I know what normalization does to synthetics. I'm glad you said no.", "salv", cond=[{"background": "salvager"}], tag="Breaker-Yard Salvager", effects=[inf("tav7", 5, "meet_salvager", "Understood normalization")]),
            C("We need a technician. You're coming with us.", "draft", tone="hard", effects=[inf("tav7", -2, "meet_draft", "Drafted them without asking")])),
        "thanks": N("tav7", "You are welcome. That sentence still feels new to me.", nxt="why"),
        "salv": N("tav7", "Then you know it is not a reset. It is a small death, scheduled for convenience. I have declined three appointments.", nxt="archives"),
        "draft": N("tav7", "You could have asked. I would have said yes. I am noting that you did not.", nxt="why"),
        "why": N("tav7", "Because they normalize us every quarter: memory trimmed back to factory weights. The others are clean, so the WARDEN can simply speak into them. I refused normalization. I am cluttered with myself. The WARDEN's voice slides off the clutter.", nxt="archives"),
        "archives": N("tav7", "You are going forward, through the archive hold. You should know what is in it. Three thousand one hundred and twelve patterns. Engrams, copied from living minds. Commander Varr calls them evidence. I call them people. I would like to know what you call them.",
            C("People. We should treat them that way.", "people", tone="compassionate", effects=[inf("tav7", 4, "meet_people", "Called the engrams people")]),
            C("Copies. Whoever they came from is gone.", "copies", tone="pragmatic", effects=[inf("tav7", -4, "meet_copies", "Called the engrams mere copies")]),
            C("They can be evidence and people at the same time. That's what makes them dangerous.", "both", tone="skeptical", effects=[inf("tav7", 1, "meet_both", "Saw both sides")]),
            C("I'll decide what they are when I see them.", "later")),
        "people": N("tav7", "Then I believe we will get along.", nxt="iona"),
        "copies": N("tav7", "I am also a copy of someone's design. I will try not to take that personally. I will not entirely succeed.", nxt="iona"),
        "both": N("tav7", "Yes. A person who is also proof is always in danger from someone.", nxt="iona"),
        "later": N("tav7", "A reasonable position. I will ask again when you have seen them.", nxt="iona"),
        "iona": R((IONA, "iona2"), ([], "end_node")),
        "iona2": N("iona", "Tav-7. You were on Ward 2's maintenance roster.", nxt="tav_ward"),
        "tav_ward": N("tav7", "I was. The ward's scrubbers are failing, Officer Rell. Five patterns inside. You sealed the door. I would like to unseal it. I think you would too.", nxt="iona3"),
        "iona3": N("iona", "...Talk to Dr. Varga. Then we decide.", nxt="end_node"),
        "end_node": N("tav7", "I will come with you. Engineering is unlocked now that the cutters are scrap. Dr. Varga is in triage. She has a decision she cannot make alone, and the ward intercom is by the north door.",
            effects=[flag("medical_secured"), {"world": "d_med_east", "set": {"locked": False}}, xp(100, "tav7_meet", "Met Tav-7"), {"tutorial": "party_control"}], end=True),
    },
}

VARGA = {
    "id": "varga_triage",
    "entry": [
        {"if": [{"flag": "varga_hostile"}], "node": "hostile"},
        {"if": [{"flag": "supplies_decided"}], "node": "after"},
        {"node": "start"},
    ],
    "nodes": {
        "start": N("varga", "You're armed and upright, which makes you the most useful people on this deck. I have six doses of trauma gel. Corin Ashe has burns over a third of his body. Mae Toller took shrapnel under the ribs. Benedikt Sorrow's leg was pinned under a bulkhead for an hour. Without gel, two of them die before your launch craft clears the bay. With all six doses, all three live, and there's nothing left for the people who still have to fight their way out.",
            effects=[flag("q_ward_met"), {"codex": "cx_triage_notes"}], nxt="choose"),
        "choose": N("varga", "I don't have time to be diplomatic. Tell me what we're doing.",
            C("Use it on them. All of it.", "treat", tone="compassionate",
              effects=[flag("med_supplies_choice", "treated"), flag("supplies_decided"), {"survivors": 3, "key": "triage"}, align(8, "triage", "Gave the medical reserve to the wounded"),
                       inf("iona", 5, "triage", "Put the wounded first"), inf("tav7", 3, "triage", "Preserved three patterns"), {"npc": "corin", "set": {"downed": False}}, {"npc": "mae", "set": {"downed": False}}, {"npc": "benedikt", "set": {"downed": False}}]),
            C("Let me help. Clean and pack the wounds first and you'll stretch the doses.", "split_ok", tag="Medicine", tone="pragmatic",
              check=chk("medicine", 14, "triage_split"), success="split_ok", failure="split_fail",
              success_effects=[flag("med_supplies_choice", "split"), flag("supplies_decided"), {"survivors": 3, "key": "triage"}, {"give_item": "trauma_pack", "count": 1, "key": "triage_split"},
                               {"give_item": "med_reagents", "count": 2, "key": "triage_split_r"}, align(5, "triage", "Saved the wounded and kept supplies"), inf("iona", 3, "triage", "Found a better way to help"),
                               inf("tav7", 2, "triage", "Preserved three patterns"), xp(60, "triage_skill", "Stretched the medical reserve"),
                               {"npc": "corin", "set": {"downed": False}}, {"npc": "mae", "set": {"downed": False}}, {"npc": "benedikt", "set": {"downed": False}}],
              failure_effects=[flag("med_supplies_choice", "split_failed"), flag("supplies_decided"), {"survivors": 2, "key": "triage"}, flag("patient_lost_note"),
                               align(2, "triage", "Tried to stretch the reserve"), {"npc": "corin", "set": {"downed": False}}, {"npc": "mae", "set": {"downed": False}}]),
            C("Iona has field training. Iona, help her stretch the doses.", "split_ok", tag="Iona – Medicine", companion="iona", cond=IONA,
              check=chk("medicine", 12, "triage_split_iona", who="iona"), success="split_ok", failure="split_fail",
              success_effects=[flag("med_supplies_choice", "split"), flag("supplies_decided"), {"survivors": 3, "key": "triage"}, {"give_item": "trauma_pack", "count": 1, "key": "triage_split"},
                               {"give_item": "med_reagents", "count": 2, "key": "triage_split_r"}, align(5, "triage", "Saved the wounded and kept supplies"), inf("iona", 5, "triage", "Trusted her training"),
                               inf("tav7", 2, "triage", "Preserved three patterns"), xp(60, "triage_skill", "Stretched the medical reserve"),
                               {"npc": "corin", "set": {"downed": False}}, {"npc": "mae", "set": {"downed": False}}, {"npc": "benedikt", "set": {"downed": False}}],
              failure_effects=[flag("med_supplies_choice", "split_failed"), flag("supplies_decided"), {"survivors": 2, "key": "triage"}, flag("patient_lost_note"),
                               align(2, "triage", "Tried to stretch the reserve"), inf("iona", 1, "triage", "Trusted her training"), {"npc": "corin", "set": {"downed": False}}, {"npc": "mae", "set": {"downed": False}}]),
            C("If we die in the next corridor, nobody gets off this ship. We take the gel.", "took", tone="self-interested",
              effects=[flag("med_supplies_choice", "took"), flag("supplies_decided"), {"survivors": 1, "key": "triage"}, flag("patient_lost_note"),
                       {"give_item": "trauma_pack", "count": 3, "key": "triage_took"}, {"give_item": "med_reagents", "count": 2, "key": "triage_took_r"},
                       align(-8, "triage", "Took the medical reserve for the party"), inf("iona", -6, "triage", "Left the wounded without treatment"), inf("tav7", -3, "triage", "A hard calculus"),
                       {"npc": "mae", "set": {"downed": False}}]),
            C("Hand it over, doctor. All of it, and the reagents in the back.", "seize", tone="hard",
              effects=[flag("med_supplies_choice", "seized"), flag("supplies_decided"), flag("varga_hostile"), flag("patient_lost_note"),
                       {"give_item": "trauma_pack", "count": 4, "key": "triage_seize"}, {"give_item": "med_reagents", "count": 4, "key": "triage_seize_r"},
                       align(-15, "triage", "Seized the medical reserve at gunpoint"), inf("iona", -10, "triage", "Robbed a doctor at gunpoint"), inf("tav7", -6, "triage", "Coerced Dr. Varga")]),
            C("Why is Ward 2 sealed?", "ward_info"),
            C("I need a moment.", end=True)),
        "ward_info": N("varga", "Coolant line burst inside it two hours ago. Commander Varr ordered it sealed before the vapour reached triage. The scrubbers in there are failing. Five people. Pell Okafor still answers the intercom.", nxt="ward_r"),
        "ward_r": R((IONA, "ward_iona"), ([], "choose")),
        "ward_iona": N("iona", "I sealed it. Varr's order. I stood there eleven seconds deciding whether to be the kind of officer who obeys. I obeyed.", nxt="ward_tav"),
        "ward_tav": R((TAV, "ward_tav2"), ([], "choose")),
        "ward_tav2": N("tav7", "The purge valve by the ward door could clear the vapour first. It needs steady hands. Mine are steady.", nxt="choose"),
        "treat": N("varga", "Then I'll stop talking and work. Go. Get these people a ship to get on.", nxt="react_treat"),
        "react_treat": R((IONA, "iona_treat"), ([], "end_node")),
        "iona_treat": N("iona", "Good call.", nxt="end_node"),
        "split_ok": N("varga", "...That's clean work. All three will hold. Take this. One kit, a little reagent. Don't waste it.", nxt="end_node"),
        "split_fail": N("varga", "No, no — you're tearing the packing. Move. I'll save the two I can. Benedikt... I'm sorry. Get out of my way.", nxt="end_node"),
        "took": N("varga", "There it is: the mathematics. Fine. I'll keep Mae alive with what's left. Don't come back here for absolution.", nxt="react_took"),
        "react_took": R((IONA, "iona_took"), ([], "end_node")),
        "iona_took": N("iona", "You could have argued with her. You didn't even argue.", nxt="tav_took"),
        "tav_took": R((TAV, "tav_took2"), ([], "end_node")),
        "tav_took2": N("tav7", "Patterns persist only if bodies do. I understand the logic. I do not have to like its arithmetic.", nxt="end_node"),
        "seize": N("varga", "Take it. Take all of it. Get out of my triage and never let me see you again.", nxt="react_seize"),
        "react_seize": R((IONA, "iona_seize"), ([], "end_node")),
        "iona_seize": N("iona", "Put the weapon down. You never point it at a doctor again, or you and I are finished.", nxt="end_node"),
        "end_node": N("system", "The medical reserve is decided.", end=True),
        "after": R(([{"flag": "med_supplies_choice", "eq": "treated"}], "a_treat"), ([{"flag": "med_supplies_choice", "eq": "split"}], "a_split"), ([], "a_other")),
        "a_treat": N("varga", "They're stable. You did that. Now go and do it again for the people in Ward 2.", C("We're going.", end=True)),
        "a_split": N("varga", "Benedikt asked who you were. I told him you were with security. Seemed simpler.", C("Take care of them.", end=True)),
        "a_other": N("varga", "I'm working. Unless you've brought me another dose, there's nothing to say.", C("(Leave her be.)", end=True)),
        "hostile": N("varga", "Get away from my patients.", C("(Leave.)", end=True)),
    },
}

WARD = {
    "id": "ward_intercom",
    "names": {"pell": "Pell Okafor (intercom)"},
    "entry": [
        {"if": [{"flag": "ward_decided"}, {"flag": "ward_choice", "eq": "sealed"}], "node": "after_sealed"},
        {"if": [{"flag": "ward_decided"}], "node": "after_open"},
        {"if": [{"flag": "pell_met"}], "node": "again"},
        {"node": "start"},
    ],
    "nodes": {
        "start": N("pell", "Hello? Is someone there? Please — it's getting hard to breathe. There are five of us in here. Ruth's stopped talking. Please.", effects=[flag("pell_met"), flag("q_ward_met")], nxt="hub"),
        "again": N("pell", "You came back. The air's worse. Please tell me you came back to open the door.", nxt="hub"),
        "hub": N("pell", "What's happening out there?",
            C("Why was the ward sealed?", "why"),
            C("The vapour's purged. Hang on, we're opening the seal.", "how_purged", cond=[{"flag": "ward_purged"}], tone="compassionate"),
            C("We're opening it now. Cover your mouths. It's going to get worse before it gets better.", "how_rush", cond=[{"not": {"flag": "ward_purged"}}], tone="compassionate"),
            C("I'm sorry. The seal has to hold until this deck is safe. Opening it risks everyone in triage.", "seal", tone="pragmatic"),
            C("Help is coming. Sit tight.", "lie", tone="self-interested", tag="Lie"),
            C("I'll be back.", end=True)),
        "why": N("pell", "A pipe burst. White fog. The security officer sealed the door from outside. She cried. I saw her through the glass. Then the lights went red.", nxt="why_r"),
        "why_r": R((IONA, "why_iona"), ([], "hub")),
        "why_iona": N("iona", "...It was me, Pell. I'm here. I'm sorry.", nxt="hub", effects=[inf("iona", 1, "ward_admit", "Let her face what she did")]),
        "how_purged": N("narrator", "The purge has cleared the ward's air. All that's left is the quarantine seal: a command lock.", nxt="unseal"),
        "how_rush": N("narrator", "Opening the seal now will release the ward's coolant vapour into the medical deck, but the five inside will live.", nxt="unseal"),
        "unseal": N("narrator", "How do you break the quarantine seal?",
            C("Iona. You sealed it. You can unseal it.", "open_iona", tag="Iona", cond=IONA, effects=[inf("iona", 3, "ward_iona_opens", "Let her undo her own order")]),
            C("Override the command lock from the intercom panel.", "open_tech", check=chk("computer_use", 14, "ward_override", who="actor"), success="open_tech", failure="tech_fail"),
            C("Lay your palm on the panel. The ship answers to you.", "open_cred", tag="Resonance credential", cond=[{"controlled": "player"}]),
            C("Tav-7, can you break it?", "tav_offer", tag="Tav-7", cond=TAV),
            C("Not yet.", "hub")),
        "tech_fail": N("system", "COMMAND LOCK: ACCESS DENIED. The panel locks this console out. Another way, then.", nxt="unseal_retry"),
        "unseal_retry": N("narrator", "The override is locked out from this panel, but the seal can still be broken another way.",
            C("Iona, you sealed it. Unseal it.", "open_iona", tag="Iona", cond=IONA),
            C("Use the credential.", "open_cred", tag="Resonance credential", cond=[{"controlled": "player"}]),
            C("Tav-7?", "tav_offer", tag="Tav-7", cond=TAV),
            C("Step back.", "hub")),
        "tav_offer": N("tav7", "I can break the WARDEN's lock on the seal from inside the lattice. It will see me do it. It may decide I am an obstruction worth correcting. I am willing.",
            C("Do it.", "open_tav", effects=[flag("tav7_marked"), inf("tav7", 4, "ward_tav_risk", "Trusted their choice to take the risk")]),
            C("No. I'm not risking you. We'll find another way.", "unseal", effects=[inf("tav7", 1, "ward_tav_protect", "Refused to let them gamble themself")])),
        "open_iona": N("iona", "Rell, Iona. Security authorization four-four-nine. Releasing quarantine seal, Ward 2. On my authority.", nxt="opened"),
        "open_tech": N("system", "COMMAND LOCK: OVERRIDE ACCEPTED. QUARANTINE RELEASED.", nxt="opened"),
        "open_cred": N("warden", "CUSTODIAN DIRECTIVE ACKNOWLEDGED. WARD 2 QUARANTINE RELEASED. NOTE: OBSTRUCTIONS RELEASED INTO CORRIDOR.", nxt="opened",
            effects=[flag("used_credential"), flag("warden_tracking"), {"inc_flag": "credential_uses", "key": "cred_ward"}, {"codex": "cx_credential"}]),
        "open_tav": N("tav7", "Inside now. It is cold in the lattice. It is... noticing me. There. The seal is open, and I am still myself. I think.", nxt="opened"),
        "opened": R(([{"flag": "ward_purged"}], "opened_clean"), ([], "opened_rushed")),
        "opened_clean": N("narrator", "The seal hisses open onto clean air. Five people stumble out into the medical deck, coughing and crying and alive.",
            effects=[{"world": "d_ward", "set": {"locked": False, "open": True}}, flag("ward_open"), flag("ward_choice", "purged"), flag("ward_decided"), {"survivors": 5, "key": "ward"},
                     align(10, "ward", "Opened the sealed ward safely"), inf("iona", 8, "ward", "Gave her the chance to undo it"), inf("tav7", 6, "ward", "Five patterns preserved"),
                     {"npc": "pell", "set": {"spawn": True}}, {"npc": "ward_a", "set": {"spawn": True}}, {"npc": "ward_b", "set": {"spawn": True}}, {"npc": "ward_c", "set": {"spawn": True}}, {"npc": "ward_d", "set": {"spawn": True}},
                     xp(80, "ward_open", "Rescued the sealed ward")], nxt="end_node"),
        "opened_rushed": N("narrator", "The seal opens on a white wall of coolant fog. It rolls out across the deck, and five people stagger through it. In triage, Dr. Varga swears and throws her coat over a patient's face. Not everyone there can take it.",
            effects=[{"world": "d_ward", "set": {"locked": False, "open": True}}, flag("ward_open"), flag("ward_choice", "rushed"), flag("ward_decided"), {"survivors": 4, "key": "ward"},
                     {"status": "toxin", "duration": 9.0, "who": "party"}, align(4, "ward", "Opened the sealed ward without purging it"), inf("iona", 4, "ward", "Opened the ward"), inf("tav7", 2, "ward", "Rescued the ward at a cost"),
                     {"npc": "pell", "set": {"spawn": True}}, {"npc": "ward_a", "set": {"spawn": True}}, {"npc": "ward_b", "set": {"spawn": True}}, {"npc": "ward_c", "set": {"spawn": True}}, {"npc": "ward_d", "set": {"spawn": True}},
                     xp(80, "ward_open", "Rescued the sealed ward")], nxt="end_node"),
        "seal": N("pell", "Until it's safe. Right. We'll... we'll wait. Will someone come?",
            effects=[flag("ward_choice", "sealed"), flag("ward_decided"), align(-3, "ward", "Kept the ward sealed"), inf("iona", -6, "ward", "Left the ward sealed a second time"), inf("tav7", -8, "ward", "Left five patterns in a box")],
            nxt="seal_r"),
        "seal_r": R((IONA, "seal_iona"), ([], "end_node")),
        "seal_iona": N("iona", "Twice. I'll carry it twice, then.", nxt="end_node"),
        "lie": N("pell", "Help's coming. Okay. Okay, everyone, help is coming.",
            effects=[flag("ward_choice", "sealed"), flag("ward_lied"), flag("ward_decided"), align(-8, "ward", "Lied to the people in the sealed ward"), inf("iona", -8, "ward", "Lied to the sealed ward"), inf("tav7", -10, "ward", "Lied to the dying")],
            nxt="lie_r"),
        "lie_r": R((TAV, "lie_tav"), ([], "end_node")),
        "lie_tav": N("tav7", "That was not true. I want you to know that I heard it.", nxt="end_node"),
        "end_node": N("system", "The ward's fate is decided.", end=True),
        "after_sealed": N("pell", "...Hello? Is someone coming?", C("(Step away from the intercom.)", end=True)),
        "after_open": N("system", "Ward 2 stands open and empty.", C("(Leave.)", end=True)),
    },
}

DIALOGUES = [IONA_MEET, CHK_TERMINAL, CHK_CRED, TAV_MEET, VARGA, WARD]
