# Act 2: engineering, archive hold, Senna Thorne, the reclaimer squad, command intercom.

ENG_TERMINAL = {
    "id": "engineering_terminal",
    "entry": [{"node": "start"}],
    "nodes": {
        "start": N("system", "ENGINEERING GRID — DRIVE CORE RING. Guest session. Coolant pressure: CRITICAL. Deck grid: FAULT (south arc).",
            C("Download the deck schematic.", "schem", cond=[{"not": {"flag": "eng_schematic"}}]),
            C("Read the WARDEN system architecture file.", "spec"),
            C("Check coolant pump status.", "pumps"),
            C("Isolate the faulty deck plate grid.", "plates_ok", cond=[{"not": {"flag": "plates_disabled"}}],
              check=chk("computer_use", 13, "eng_plates", who="actor"), success="plates_ok", failure="plates_fail",
              success_effects=[flag("plates_disabled"), xp(40, "plates", "Isolated the live deck plates")]),
            C("Overload the deck plating under the WARDEN Sentinel's post.", "overload_ok", cond=[{"not": {"cleared": "enc_engineering"}}, {"not": {"flag": "eng_overloaded"}}],
              check=chk("computer_use", 16, "eng_overload", who="actor"), success="overload_ok", failure="overload_fail",
              success_effects=[flag("eng_overloaded"), {"area_damage": [108.0, 8.0], "radius": 7.0, "dice": "2d6", "dtype": "energy", "status": "stunned", "duration": 6.0, "faction": "warden"},
                               {"start_encounter": "enc_engineering"}, xp(30, "eng_overload", "Turned the deck grid on the Sentinel")],
              failure_effects=[{"start_encounter": "enc_engineering"}]),
            C("Log off.", end=True)),
        "schem": N("system", "Schematic downloaded: engineering ring, workshop, maintenance duct to the archive hold.", nxt="start",
            effects=[flag("eng_schematic"), {"reveal_area": ["engineering", "workshop", "duct"]}, xp(15, "eng_schem", "Downloaded the engineering schematic")]),
        "spec": N("system", "WARDEN: integrated defense lattice. Cognitive root: CUSTODIAN TEMPLATE (classified).", nxt="spec_r", effects=[{"codex": "cx_warden_spec"}]),
        "spec_r": R((TAV, "spec_tav"), ([], "start")),
        "spec_tav": N("tav7", "Its root is a person's pattern. A human operator's judgment, grown into a defense network. That would explain why its voice feels like someone and not something.", nxt="start"),
        "pumps": N("system", "NORTH PUMP: SEAL FAILURE. SOUTH PUMP: SEAL FAILURE. Seal template SL-4 is loaded at the workshop bench (fabricate: 2 technical components).", nxt="start", effects=[flag("pump_seal_known")]),
        "plates_ok": N("system", "SOUTH ARC GRID: ISOLATED. The sparking along the deck dies away.", nxt="start"),
        "plates_fail": N("system", "GRID CONTROL REJECTED. The plates are still live; the junction box in the south arc can isolate them by hand.", nxt="start"),
        "overload_ok": N("system", "EAST ARC DECK: POWER SURGE. Somewhere around the curve of the ring, metal screams and something heavy falls over.", end=True),
        "overload_fail": N("system", "SURGE ABORTED. WARDEN SENTINEL ALERTED.", end=True),
    },
}

ARCHIVE_INDEX = {
    "id": "archive_index",
    "entry": [
        {"if": [{"flag": "index_open"}], "node": "hub"},
        {"node": "start"},
    ],
    "nodes": {
        "start": N("system", "ARCHIVE INDEX — CINDER WAKE HOLD. RESTRICTED: COMMAND AND CUSTODIAN ONLY.",
            C("Slice the index.", "opened", check=chk("computer_use", 14, "arc_index", who="actor"), success="opened", failure="locked"),
            C("Tav-7, can you talk to it?", "opened", tag="Tav-7 – Computer Use", cond=TAV, check=chk("computer_use", 12, "arc_index_tav", who="tav7"), success="opened", failure="locked_tav"),
            C("Authenticate with your neural signature.", "opened_cred", tag="Resonance credential", cond=[{"controlled": "player"}]),
            C("Read the physical labels on the cylinders instead.", "labels"),
            C("Log off.", end=True)),
        "locked": N("system", "ACCESS DENIED. This console locks out for the session. The cylinders themselves have printed labels.", nxt="start"),
        "locked_tav": N("tav7", "It does not want to talk to me. It knows I refused normalization. Perhaps another way.", nxt="start"),
        "labels": N("narrator", "Each cylinder carries a strip label: an index number, a camp code — VESPER, CALLAN — and a name. Hundreds of names. The label on the nearest one reads 0441 DARROW, E.", nxt="start",
            effects=[flag("archive_evidence_stolen"), {"codex": "cx_harvest"}]),
        "opened_cred": N("warden", "CUSTODIAN ACCESS. INDEX UNSEALED. You do not need to ask, Source. Everything here is yours to see.", nxt="opened",
            effects=[flag("used_credential"), flag("warden_tracking"), {"inc_flag": "credential_uses", "key": "cred_index"}]),
        "opened": N("system", "INDEX OPEN. 3,112 records. Program: DIRECTIVE 9 — PATTERN HARVEST.", nxt="hub", effects=[flag("index_open"), xp(50, "arc_index_open", "Opened the archive index")]),
        "hub": N("system", "The index waits.",
            C("Read the program summary.", "harvest"),
            C("Open engram 0441: Vesper Station.", "vesper"),
            C("Copy engram 0441 to a data spike.", "copy", cond=[{"flag": "vesper_read"}, {"not": {"flag": "vesper_recovered"}}]),
            C("Search the index for 'custodian'.", "custodian"),
            C("Close the index.", end=True)),
        "harvest": N("system", "DIRECTIVE 9. Engrams archived: 3,112. Source: Haldis detainees. Consent: not required (security exemption). Purpose: operator training substrate; custodian template validation.", nxt="harvest_r",
            effects=[flag("archive_evidence_stolen"), {"codex": "cx_harvest"}]),
        "harvest_r": R((TAV, "harvest_tav"), (IONA, "harvest_iona"), ([], "hub")),
        "harvest_tav": N("tav7", "'Consent: not required.' Three thousand people, and the field for their consent says not required.", nxt="harvest_iona_r"),
        "harvest_iona_r": R((IONA, "harvest_iona"), ([], "hub")),
        "harvest_iona": N("iona", "And we were told it was medical archive cores. I signed the cargo manifest.", nxt="hub"),
        "vesper": N("system", "ENGRAM 0441 — DARROW, ESHE, CORPORAL, CONCORD GARRISON, VESPER STATION. Playback: forty minutes.", nxt="vesper2",
            effects=[flag("archive_evidence_atrocity"), flag("vesper_read"), {"codex": "cx_vesper"}]),
        "vesper2": N("narrator", "You only let it run for a minute. It is enough: the singing at the gate, the cold attention settling behind Darrow's eyes, her hands rising without her. You know that attention. You were taught how to be it.",
            C("Close it. I've seen enough.", "hub"),
            C("(Let the rest play. Someone should witness all of it.)", "witness", effects=[align(4, "vesper_witness", "Witnessed the Vesper testimony in full")])),
        "witness": N("narrator", "Forty minutes. When it ends, your hands are steady and your face is wet.", nxt="hub", effects=[xp(30, "vesper_witness", "Witnessed the Vesper testimony")]),
        "copy": N("system", "ENGRAM 0441 COPIED TO DATA SPIKE. Original retained.", nxt="hub",
            effects=[{"give_item": "vesper_testimony", "count": 1, "key": "vesper_copy"}, flag("vesper_recovered")]),
        "custodian": N("system", "CUSTODIAN TEMPLATE — SOURCE RECORD SEALED. AUTHORITY: COMMAND. NOTE: CUSTODIAN PRESENT ABOARD.", nxt="cust_r"),
        "cust_r": R(([{"flag": "used_credential"}], "cust_known"), ([], "hub")),
        "cust_known": N("warden", "Present. Present. Present. You are standing at the index, Source.", nxt="hub"),
    },
}

SENNA = {
    "id": "senna",
    "names": {"senna": "Senna Thorne"},
    "entry": [
        {"if": [{"flag": "senna_decided"}], "node": "after"},
        {"node": "start"},
    ],
    "nodes": {
        "start": N("senna", "Stop there. I've got a pistol and a hole in my side, and I'm not sure which one gives out first. Concord?",
            effects=[flag("senna_met"), flag("senna_found")], *[
            C("Easy. I'm not here to kill you. Passenger, trying to reach the launch bay.", "who", tone="compassionate"),
            C("Drop the pistol. Now.", "drop", tone="hard"),
            C("(In Haldis dialect) Light goes home, sister. Put it down.", "dialect", tag="Haldis Native", cond=[{"background": "colonist"}], effects=[xp(30, "senna_dialect", "Spoke to Senna in her own tongue")]),
            C("Who are you, and why are you bleeding in a refrigerator?", "who", tone="skeptical")]),
        "drop": N("senna", "Or what? You'll shoot me? Get in line behind your ship. ...Fine. It's down. I couldn't lift it again anyway.", nxt="who"),
        "dialect": N("senna", "...Where did a Concord passenger learn to say that? The pistol's down. Don't make me regret it.", nxt="who", effects=[flag("senna_trust")]),
        "who": N("senna", "Senna Thorne. Lantern Office, scout section. The cutters caught me in the aisle. My squad thinks I'm dead, probably. We came for the hold.",
            C("What's in the hold, from your side?", "lantern"),
            C("Your people boarded a refugee ship with breaching charges.", "charges", tone="hard"),
            C("You need that wound treated.", "treat_offer", tone="compassionate")),
        "lantern": N("senna", "Our dead. The Concord kept prisoners at Vesper and Callan. The Lattice copied them before they died, or instead of letting them live. Three thousand people. On Haldis we carry the dead to a lantern hall and speak their names into flame so their light goes home. The Assembly wants them home. That's all. You keep calling it evidence. We call it Grandmother.",
            effects=[{"codex": "cx_lantern"}], nxt="lantern_r"),
        "lantern_r": R((TAV, "lantern_tav"), ([], "decide")),
        "lantern_tav": N("tav7", "Then we agree on what they are, Senna Thorne. We may not agree on what to do with them.", nxt="decide"),
        "charges": N("senna", "We cut into a ship that was running away with our families in its hold. Your WARDEN started killing passengers before we finished the first breach. Pick who you hate. I'm too tired to argue.", nxt="decide"),
        "treat_offer": N("senna", "You'd do that? For a reclaimer?", nxt="decide"),
        "decide": N("senna", "So. What happens to me?",
            C("Hold still. I'm going to treat that.", "treat_ok", tag="Medicine", tone="compassionate", check=chk("medicine", 12, "senna_treat"), success="treat_ok", failure="treat_bad",
              success_effects=[flag("senna_fate", "treated"), flag("senna_message"), flag("lantern_passphrase"), flag("senna_decided"), align(6, "senna", "Treated a wounded enemy scout"),
                               inf("iona", 3, "senna", "Showed mercy to a wounded combatant"), inf("tav7", 3, "senna", "Preserved Senna Thorne"), xp(60, "senna_skill", "Treated Senna's wound")],
              failure_effects=[flag("senna_fate", "treated"), flag("senna_message"), flag("lantern_passphrase"), flag("senna_decided"), align(4, "senna", "Tried to treat a wounded enemy scout"),
                               inf("iona", 2, "senna", "Showed mercy to a wounded combatant"), inf("tav7", 2, "senna", "Tried to preserve Senna Thorne")]),
            C("Use a medpac on her.", "treat_ok", cond=[{"item": "medpac"}], effects=[{"take_item": "medpac", "count": 1}, flag("senna_fate", "treated"), flag("senna_message"), flag("lantern_passphrase"), flag("senna_decided"),
              align(6, "senna", "Gave a medpac to a wounded enemy scout"), inf("iona", 3, "senna", "Showed mercy to a wounded combatant"), inf("tav7", 3, "senna", "Preserved Senna Thorne")]),
            C("Tell me your squad's passphrase, or I leave you here for the cutters.", "intim_ok", tag="Persuasion (intimidate)", tone="hard", check=chk("persuasion", 14, "senna_intim"), success="intim_ok", failure="intim_fail",
              success_effects=[flag("senna_fate", "interrogated"), flag("lantern_passphrase"), flag("senna_decided"), align(-6, "senna", "Threatened a wounded prisoner"), inf("iona", -3, "senna", "Threatened a wounded prisoner")],
              failure_effects=[flag("senna_fate", "interrogated"), flag("senna_decided"), align(-6, "senna", "Threatened a wounded prisoner"), inf("iona", -3, "senna", "Threatened a wounded prisoner")]),
            C("Help me reach the bay safely, and I'll see your people get what they came for.", "bargain", tone="pragmatic",
              effects=[flag("senna_fate", "bargained"), flag("senna_message"), flag("lantern_passphrase"), flag("promised_lantern"), flag("senna_decided"),
                       inf("tav7", 3, "senna", "Promised the dead would go home"), inf("iona", -1, "senna", "Promised away the cargo")]),
            C("Go. Find your people. Tell them who let you walk.", "release", tone="compassionate",
              effects=[flag("senna_fate", "released"), flag("senna_message"), flag("senna_decided"), align(3, "senna", "Let a wounded scout go"), inf("iona", 1, "senna", "Let her go")]),
            C("You boarded a refugee ship. This ends here.", "kill_confirm", tone="hard")),
        "kill_confirm": N("narrator", "Senna sees it in your face before you move. She doesn't beg. She closes her eyes and starts saying names under her breath.",
            C("(Do it.)", "killed", effects=[flag("senna_fate", "killed"), flag("senna_decided"), align(-15, "senna", "Executed a wounded prisoner"),
                                            inf("iona", -8, "senna", "Executed a wounded prisoner"), inf("tav7", -10, "senna", "Ended Senna Thorne's pattern"), {"npc": "senna", "set": {"kill": True}}]),
            C("(Stop. Lower your weapon.)", "decide")),
        "treat_ok": N("senna", "Hah — that stings. ...Thank you. Listen. My squad is in the central aisle: Abeni, Rusk, and Dov. If they see you, say 'ember-tide' and say Senna sent you. They'll listen. And if you reach Bay 2, tell Marshal Quill I'm alive and who to thank.", nxt="react"),
        "treat_bad": N("senna", "Gods — you've torn the packing. ...No, leave it, it'll hold long enough. The passphrase is 'ember-tide'. Tell Marshal Quill I'm alive. Tell him you tried.", nxt="react"),
        "intim_ok": N("senna", "'Ember-tide.' That's the word. I hope it chokes you. My squad will listen to it. The Marshal won't forget who taught you it.", nxt="react"),
        "intim_fail": N("senna", "You'll leave me for the cutters? Then leave. You won't get a word.", nxt="react"),
        "bargain": N("senna", "You'll see they come home? ...Then the word is 'ember-tide', and I'll tell the Marshal you gave your oath. Don't break it. We remember oaths longer than names.", nxt="react"),
        "release": N("senna", "Just... let me go? I'll tell Marshal Quill an operator let me walk. Whatever you are, I'll tell him that.", nxt="react"),
        "killed": N("narrator", "It is quick. The names stop.", nxt="react"),
        "react": R(([{"flag": "senna_fate", "eq": "killed"}], "react_kill"), ([], "end_node")),
        "react_kill": R((IONA, "kill_iona"), (TAV, "kill_tav"), ([], "end_node")),
        "kill_iona": N("iona", "She was wounded and she'd put the pistol down. That's not a fight, {name}. That's an execution, and I watched it.", nxt="kill_tav_r"),
        "kill_tav_r": R((TAV, "kill_tav"), ([], "end_node")),
        "kill_tav": N("tav7", "A pattern ended. I am recording the names she was saying. Someone should finish them.", nxt="end_node"),
        "end_node": N("system", "Senna Thorne's fate is decided.", end=True),
        "after": R(([{"flag": "senna_fate", "eq": "released"}], "after_gone"), ([], "after_wait")),
        "after_wait": N("senna", "Go on. The aisle's that way. Ember-tide, if you need it.", C("(Leave her.)", end=True)),
        "after_gone": N("narrator", "Only a smear of blood marks where Senna was hiding.", C("(Leave.)", end=True)),
    },
}

PARLEY = {
    "id": "reclaimer_parley",
    "names": {"abeni": "Reclaimer Signalist Abeni Oyelaran"},
    "entry": [{"node": "start"}],
    "nodes": {
        "start": N("abeni", "Hold! Hands where we see them. Concord, or crew? Either way, you're standing in our dead's house.",
            C("Ember-tide. Senna sent me. She's alive, in cold storage.", "pass", tag="Passphrase", cond=[{"flag": "lantern_passphrase"}, {"not": {"flag": "senna_fate", "eq": "killed"}}]),
            C("Ember-tide.", "pass_dead", tag="Passphrase", cond=[{"flag": "lantern_passphrase"}, {"flag": "senna_fate", "eq": "killed"}]),
            C("(Show the kinship token.) I'm owed a hearing.", "token", tag="Haldis kinship token", cond=[{"item": "kinship_token"}]),
            C("The WARDEN is killing everyone aboard, us and you. We're not your enemy. Let us pass to command.", "talked", tag="Persuasion", tone="pragmatic",
              check=chk("persuasion", 15, "parley_persuade", bonus_if=[{"if": [{"flag": "archive_evidence_stolen"}], "bonus": 2}]), success="talked", failure="fight"),
            C("You're three. We're armed, and we've had a very bad day. Walk away.", "withdraw", tag="Persuasion (intimidate)", tone="hard",
              check=chk("persuasion", 16, "parley_intim"), success="withdraw", failure="fight"),
            C("(Lean on their fear with Resonance.)", "swayed", tone="hard", check=chk("persuasion", 14, "parley_sway", power="sway", energy=3), success="swayed", failure="fight",
              effects=[align(-5, "parley_sway", "Pushed the reclaimers' minds with Resonance"), inf("iona", -2, "parley_sway", "Coerced the reclaimers"), inf("tav7", -3, "parley_sway", "Overrode their will")]),
            C("Then we do this the hard way.", "fight_now", tone="hard")),
        "pass": N("abeni", "Ember-tide... Senna's alive? Rusk, Dov, lower them. You saved a lantern-keeper. The hall owes you a light. Go on to your command chamber. We will not touch you.", nxt="peace",
            effects=[inf("tav7", 2, "parley_pass", "Ended a fight without bloodshed")]),
        "pass_dead": N("abeni", "Where did you get that word? Where is Senna? ...You don't answer. Rusk, Dov — they've got her word and not her. Weapons up!", nxt="fight"),
        "token": N("abeni", "A kinship glyph. Haldis-born. All right, kin. You get your hearing. Talk fast.",
            C("We're getting passengers off this ship. That's all. The hold is your business, not ours.", "talked", check=chk("persuasion", 10, "parley_token"), success="talked", failure="fight"),
            C("Let us through and I'll speak for your dead at command.", "talked", check=chk("persuasion", 10, "parley_token2"), success="talked", failure="fight")),
        "talked": N("abeni", "...Fine. Go. If you're lying, the Marshal will be in Bay 2 to explain our position more thoroughly.", nxt="peace"),
        "swayed": N("narrator", "You reach into the space behind their eyes and press. Rusk's rifle dips first. Then Abeni's. They step aside without quite knowing why.", nxt="peace"),
        "withdraw": N("abeni", "...Pull back. Back to the breach. We'll take this to the Marshal.", nxt="fled"),
        "peace": N("system", "The reclaimers stand aside.", effects=[flag("archive_peace"), {"resolve_encounter": "enc_archive", "resolution": "parley"}, xp(40, "parley", "Talked past the reclaimer squad")], end=True),
        "fled": N("system", "The reclaimers withdraw toward the dorsal breach. You'll likely see them again.", effects=[flag("archive_bypassed"), {"resolve_encounter": "enc_archive", "resolution": "withdrew"}], end=True),
        "fight_now": N("abeni", "Your choice. Lanterns up!", nxt="fight"),
        "fight": N("system", "The reclaimers open fire.", effects=[{"start_encounter": "enc_archive"}], end=True),
    },
}

INTERCOM = {
    "id": "command_intercom",
    "names": {"varr": "Commander Ysolde Varr (intercom)"},
    "entry": [
        {"if": [{"flag": "command_open"}], "node": "open_already"},
        {"if": [{"encounter": "enc_archive", "state": "active"}], "node": "busy"},
        {"node": "start"},
    ],
    "nodes": {
        "start": N("varr", "This is Commander Varr. You're standing at my door in a hold full of boarders. Identify yourself.",
            C("Commander, it's Rell. I have passengers' escorts with me. Open the door.", "iona", tag="Iona", cond=IONA),
            C("{name}, passenger. We're going to Bay 2, and Bay 2 is through you.", "plain"),
            C("WARDEN. Open the command door.", "cred", tag="Resonance credential", cond=[{"controlled": "player"}]),
            C("You need us more than we need you, Commander. You're sealed in a room with no guards.", "persuade", tag="Persuasion", check=chk("persuasion", 12, "intercom_persuade"), success="persuade", failure="plain_fail")),
        "iona": N("varr", "Rell. You're alive. ...Fine. Come in, all of you. Slowly.", nxt="open"),
        "plain": N("varr", "A passenger. With a Lumen Edge, I imagine. ...I've been expecting you. Come in.", nxt="open"),
        "plain_fail": N("varr", "Nice try. But you're right about the guards. Come in, slowly.", nxt="open"),
        "persuade": N("varr", "...You're not wrong. Come in.", nxt="open", effects=[xp(30, "intercom_persuade", "Talked Varr into opening command")]),
        "cred": N("warden", "CUSTODIAN PRIORITY EXCEEDS COMMAND. DOOR OPENING.", nxt="cred2",
            effects=[flag("used_credential"), flag("varr_overridden"), {"inc_flag": "credential_uses", "key": "cred_command"}]),
        "cred2": N("varr", "WARDEN, belay — of course. Of course it opens for you. Get in here.", nxt="open"),
        "open": N("system", "The command chamber's blast door grinds open.", effects=[flag("command_open"), {"world": "d_command", "set": {"locked": False, "open": True}}], end=True),
        "busy": N("varr", "Not with reclaimers shooting at my door! Deal with them and then we'll talk.", C("(Close the intercom.)", end=True)),
        "open_already": N("system", "The door is already open.", C("(Close.)", end=True)),
    },
}

DIALOGUES = [ENG_TERMINAL, ARCHIVE_INDEX, SENNA, PARLEY, INTERCOM]
