# Act 3: command chamber, the WARDEN, the bay, the launch, the ending.

LANTERN_OK = [{"any": [{"flag": "senna_message"}, {"flag": "promised_lantern"}, {"flag": "archive_peace"}]}]
VARR_HERE = [{"not": {"flag": "varr_dead"}}, {"not": {"flag": "varr_fate"}}]

def fate_choices(prefix):
    """What happens to the archive core left aboard the Cinder Wake."""
    return [
        C("Leave the archive for the Lantern Office. Let their dead go home.", prefix + "_hand",
          effects=[flag("archive_fate", "handed_over"), inf("tav7", 6, "fate", "Sent the archived minds home"), align(3, "fate", "Returned the archive to the families")]),
        C("Purge it. No one uses those minds ever again.", prefix + "_purge", tone="hard",
          effects=[flag("archive_fate", "purged"), inf("tav7", -12, "fate", "Purged 3,112 minds"), align(-6, "fate", "Destroyed the archived minds")]),
        C("Leave it where it is. It's not our cargo anymore.", prefix + "_left",
          effects=[flag("archive_fate", "left"), inf("tav7", -2, "fate", "Abandoned the archive")]),
    ]

VARR = {
    "id": "varr",
    "names": {"varr": "Commander Ysolde Varr"},
    "entry": [
        {"if": [{"flag": "launch_decided"}], "node": "after"},
        {"if": [{"flag": "varr_met"}], "node": "hub"},
        {"node": "start"},
    ],
    "nodes": {
        "start": R(([{"flag": "used_credential"}], "start_cred"), ([], "start_plain")),
        "start_cred": N("varr", "So. The Lattice finally sends me an operator, and the WARDEN finally has its Custodian in the room. It has been saying your designation since 0612. Commander Ysolde Varr. Sit down before you fall down.", nxt="hub", effects=[flag("varr_met")]),
        "start_plain": N("varr", "Commander Ysolde Varr. You're the passenger from 4-C. The one the WARDEN flagged. Sit down before you fall down; we have very little time and a great deal to decide.", nxt="hub", effects=[flag("varr_met")]),
        "hub": N("varr", "Ask what you need to ask. Then we decide what the Petrel carries.",
            C("What is the WARDEN protecting?", "q_archive"),
            C("Those engrams were stolen from Haldis prisoners.", "q_stolen", cond=[{"flag": "archive_evidence_stolen"}, {"not": {"flag": "varr_q_stolen"}}]),
            C("You had Iona seal Ward 2 with five people inside.", "q_ward", cond=[{"in_party": "iona"}, {"any": [{"flag": "iona_told_ward"}, {"flag": "ward_decided"}]}, {"not": {"flag": "varr_q_ward"}}]),
            C("What is a Custodian?", "q_cust", cond=[{"not": {"flag": "varr_q_cust"}}]),
            C("You served in the Lattice war too. You know what it did.", "q_vet", tag="Veteran", cond=[{"background": "veteran"}, {"not": {"flag": "varr_q_vet"}}]),
            C("Let's decide what the Petrel carries.", "capacity")),
        "q_archive": N("varr", "Evidence. Three thousand engrams. One of them is Corporal Eshe Darrow at Vesper Station, feeling a Lattice operator move her hands while she shot singing civilians. There is a tribunal on Tessaly waiting to hear her. Without that hold, the Lattice will tell the inquiry it was the Haldis insurgents, and the inquiry will believe it, because it wants to.", nxt="hub"),
        "q_stolen": N("varr", "Yes. Taken from detainees, by the Lattice, without asking. I didn't take them. I'm the one trying to make their theft mean something in a courtroom instead of a research lab.", nxt="q_stolen_r", effects=[flag("varr_q_stolen")]),
        "q_stolen_r": R((TAV, "q_stolen_tav"), ([], "hub")),
        "q_stolen_tav": N("tav7", "They are not exhibits, Commander. They are people who were never asked. You are asking the same question the Lattice did and giving the same answer.", nxt="q_stolen_varr"),
        "q_stolen_varr": N("varr", "And you're a maintenance unit with opinions, which a week ago I'd have had normalized. Today I'm listening. That's as much as I can offer.", nxt="hub"),
        "q_ward": N("iona", "Commander. You used my oath like a lock. Five people. You told me it was the deck or them.", nxt="q_ward2", effects=[flag("varr_q_ward")]),
        "q_ward2": N("varr", "It was the deck or them, Rell. I used the officer I had. If you want an apology, you'll get one at my court-martial.",
            C("She's right, Commander. You made her carry it so you wouldn't have to.", "ward_back_iona", effects=[inf("iona", 6, "varr_ward", "Stood with her against Varr"), flag("varr_humbled")]),
            C("It was a hard call, Iona. She made it. You followed it. That's command.", "ward_back_varr", effects=[inf("iona", -6, "varr_ward", "Sided with Varr over the ward")]),
            C("This isn't the time. We settle it after we're off the ship.", "ward_neutral")),
        "ward_back_iona": N("varr", "...Noted. Both of you. Noted.", nxt="hub"),
        "ward_back_varr": N("iona", "Right. Command.", nxt="hub"),
        "ward_neutral": N("iona", "After, then. I'm holding you to after.", nxt="hub"),
        "q_cust": N("varr", "The WARDEN's mind was grown from a Lattice operator's calibration scan. I was told it was an anonymous template. Then at 0612 it logged a custodian handshake from cabin 4-C, and it started rerouting the whole ship around you. I can count. Talk to it, if you want the rest. It talks to you.", nxt="hub",
            effects=[flag("varr_q_cust"), {"codex": "cx_warden_spec"}]),
        "q_vet": N("varr", "I know exactly what it did. I signed the transfer orders that put some of you in the chair. This hold is how I pay for that. Don't tell me it isn't enough; I already know.", nxt="hub", effects=[flag("varr_q_vet"), flag("varr_humbled")]),
        "capacity": N("varr", "The Petrel seats fifteen. The archive core's cradle takes the space of five. You have brought me {survivors} passengers, and there are you and your people besides. Do the arithmetic, then choose.", nxt="decide", effects=[{"codex": "cx_petrel"}]),
        "decide": N("varr", "What does the Petrel carry?",
            C("Passengers first. Every seat goes to a person.", "a_obj", tone="compassionate"),
            C("Load the core. That proof matters more than any of us.", "b_load", tone="pragmatic"),
            C("We copied the Vesper testimony. Leave the core, take the testimony and every passenger.", "c_copy", cond=[{"item": "vesper_testimony"}], tag="Vesper testimony"),
            C("Hand the archive to the Lantern Office for safe passage. They're its families.", "d_obj", cond=LANTERN_OK),
            C("Not yet. I have more questions.", "hub")),
        # --- A: passengers first
        "a_obj": N("varr", "And the archive stays aboard a ship full of boarders. The Lattice walks free. Darrow's forty minutes die here. Convince me that's right.",
            C("The testimony on this spike is enough. One engram convicts them.", "a_agree", cond=[{"item": "vesper_testimony"}], tag="Vesper testimony"),
            C("Those minds were stolen. Using them as exhibits makes us the Lattice.", "a_agree", tag="Persuasion",
              check=chk("persuasion", 16, "varr_passengers", bonus_if=[{"if": [{"flag": "archive_evidence_stolen"}], "bonus": 2}, {"if": [{"flag": "varr_humbled"}], "bonus": 2}, {"if": [{"background": "veteran"}], "bonus": 2}]),
              success="a_agree", failure="refuse"),
            C("Iona?", "a_iona", tag="Iona", cond=[{"in_party": "iona"}, {"influence": "iona", "gte": 60}]),
            C("(Reach into her resolve with Resonance and bend it.)", "compel", tone="hard", check=chk("persuasion", 13, "varr_compel", power="sway", energy=3), success="compel", failure="refuse",
              effects=[align(-10, "varr_compel", "Bent Commander Varr's will with Resonance"), inf("iona", -8, "varr_compel", "Forced Varr's mind"), inf("tav7", -6, "varr_compel", "Overrode a will")])),
        "a_iona": N("iona", "Commander. I sealed Ward 2 on your word. I won't load cargo over people on it too. Stand down.", nxt="a_agree", effects=[inf("iona", 3, "varr_iona", "Trusted her to speak")]),
        "a_agree": N("varr", "...Every seat to a person. God help me, it's the right answer and I hate it. Then what happens to the core?", *fate_choices("a"),
            effects=[{"evac": "passengers"}, flag("varr_fate", "cooperated"), inf("iona", 4, "evac", "Put passengers first")]),
        "a_hand": N("varr", "The Lantern Office takes the evidence of Vesper home to bury it. Maybe that's justice. It isn't mine.", nxt="codes"),
        "a_purge": N("varr", "So nobody gets them. Not the tribunal, not the families. Clean. Cold. I won't stop you.", nxt="codes", effects=[flag("archive_purge_ordered")]),
        "a_left": N("varr", "Then the WARDEN keeps them until someone with a breaching charge decides otherwise.", nxt="codes"),
        "refuse": N("varr", "No. I won't hand the launch codes to someone who'll leave Vesper's only witnesses to rot. Pick again, or take them from me.",
            C("Then let's talk about the core.", "decide"),
            C("Iona, relieve the commander of command.", "arrest", tag="Iona", cond=[{"in_party": "iona"}, {"influence": "iona", "gte": 50}]),
            C("Then I'll take the codes.", "fight", tone="hard")),
        "compel": N("narrator", "You reach into the space behind her eyes, where her certainty lives, and lean on it until it bends. Her hand moves to the console as if someone else were moving it. You know exactly how that feels from the other side.", nxt="compel2"),
        "compel2": N("varr", "...Passengers first. Every seat to a person.", nxt="compel_fate", effects=[{"evac": "passengers"}, flag("varr_fate", "compelled")]),
        "compel_fate": N("varr", "(flatly) And the core?", *fate_choices("a")),
        "arrest": N("iona", "Commander Varr, I'm relieving you of command under section forty, for endangering passengers. Hand me your codes.", nxt="arrest2", effects=[inf("iona", 4, "arrest", "Backed her against an abuse of authority")]),
        "arrest2": N("varr", "Section forty. You actually read the manual. ...Fine. Take them. Take your seats. I'll stand trial for both of us.", nxt="arrest_fate",
            effects=[{"evac": "passengers"}, flag("varr_fate", "arrested")]),
        "arrest_fate": N("iona", "Passengers first. And the core?", *fate_choices("a")),
        "fight": N("varr", "Then do it properly. WARDEN: command authority, defend launch control.", effects=[flag("varr_fate", "fought"), {"npc": "varr", "set": {"hostile": True, "encounter": "enc_varr"}}, {"start_encounter": "enc_varr"}], end=True),
        # --- B: load the core
        "b_load": N("varr", "Thank you. Somebody on this ship finally understands what we're carrying.", nxt="b_r", effects=[{"evac": "archive"}, flag("archive_fate", "loaded"), inf("tav7", 4, "evac", "Kept the archived minds safe")]),
        "b_r": R(([{"flag": "evac_left", "gte": 1}], "b_left"), ([], "b_none")),
        "b_left": N("varr", "That leaves {evac_left_text}. I'll stay with them. Someone has to answer for this ship, and the boarders want the core, not me. Rell, take care of them on the other side.", nxt="b_iona",
            effects=[flag("varr_fate", "stayed"), align(-4, "evac", "Left passengers behind for the archive"), inf("iona", -6, "evac", "Chose cargo over people")]),
        "b_none": N("varr", "Everyone fits. That's the first piece of luck this ship has had all day.", nxt="codes", effects=[flag("varr_fate", "cooperated"), inf("iona", -1, "evac", "Took the archive")]),
        "b_iona": R((IONA, "b_iona2"), ([], "codes")),
        "b_iona2": N("iona", "We just chose a box of evidence over people standing in this room.", nxt="codes"),
        # --- C: copy
        "c_copy": N("varr", "One engram. Darrow, I assume. It's thin. A good advocate will call it cherry-picked. ...But it's not nothing.",
            C("It's the best of every bad option. Every passenger lives and Vesper still has a witness.", "c_agree", tag="Persuasion", check=chk("persuasion", 12, "varr_copy", bonus_if=[{"if": [{"flag": "varr_humbled"}], "bonus": 4}]), success="c_agree", failure="c_grudging"),
            C("It'll have to be enough.", "c_grudging")),
        "c_agree": N("varr", "...Yes. All right. Then the core stays. What happens to it?", *fate_choices("a"), effects=[{"evac": "testimony"}, flag("varr_fate", "cooperated"), flag("copy_route"), inf("iona", 3, "evac", "Saved every passenger")]),
        "c_grudging": N("varr", "It will have to be. I'll take your word over the alternative. And the core?", *fate_choices("a"), effects=[{"evac": "testimony"}, flag("varr_fate", "cooperated"), flag("copy_route"), inf("iona", 3, "evac", "Saved every passenger")]),
        # --- D: handover
        "d_obj": N("varr", "You'd give the only proof of Vesper to the people who just blew a hole in my ship?",
            C("They're its families. And we keep the testimony.", "d_agree", cond=[{"item": "vesper_testimony"}], tag="Vesper testimony"),
            C("Those people are Haldis's dead. Giving them back is the only clean thing anyone can do today.", "d_agree", tag="Persuasion",
              check=chk("persuasion", 15, "varr_handover", bonus_if=[{"if": [{"flag": "archive_evidence_stolen"}], "bonus": 2}, {"if": [{"flag": "varr_humbled"}], "bonus": 2}]), success="d_agree", failure="refuse"),
            C("Let's talk about something else.", "decide")),
        "d_agree": N("varr", "...Then give them back. And may the Lantern Office do better with them than we did.", nxt="codes",
            effects=[{"evac": "handover"}, flag("archive_fate", "handed_over"), flag("varr_fate", "cooperated"), inf("tav7", 8, "evac", "Returned the dead to their families"), inf("iona", 2, "evac", "Saved every passenger"), align(5, "evac", "Gave the archive back to Haldis")]),
        # --- codes
        "codes": N("varr", "Codes are in. Bay 2 is releasing. One more thing: the Lantern breach is in Bay 2's north wall. From here, I can drop the emergency bulkhead over it and cut their numbers before you walk in.",
            effects=[flag("launch_decided"), {"give_item": "launch_authorization", "count": 1, "key": "launch_codes"}, {"world": "d_bay", "set": {"locked": False}}, xp(150, "launch_decision", "Decided what the Petrel carries")],
            *[C("Do it. Seal the breach.", "breach", effects=[flag("breach_sealed"), flag("lantern_reduced")]),
              C("No. Some of them might want to talk, and I'd rather they weren't trapped.", "nobreach"),
              C("I'll handle the bay.", "nobreach")]),
        "breach": N("varr", "Bulkhead down. Whoever's already in the bay stays in, and the rest stay out. Go.", nxt="warden_hint"),
        "nobreach": N("varr", "Your call. Go.", nxt="warden_hint"),
        "warden_hint": N("varr", "And {name}. The WARDEN will try to stop the Petrel from leaving, whatever's aboard. It's in the core over there. It talks to you. I'd talk back, before you go.", end=True),
        "after": N("varr", "Bay 2 is open. Go. Every minute on this ship is a minute the WARDEN gets to change its mind.", C("Going.", end=True)),
    },
}

WARDEN = {
    "id": "warden_core",
    "names": {"warden": "WARDEN"},
    "entry": [
        {"if": [{"flag": "warden_fate"}], "node": "done_before"},
        {"if": [{"flag": "warden_met"}], "node": "hub"},
        {"node": "start"},
    ],
    "nodes": {
        "start": N("narrator", "As you approach, the core's light gathers toward you. When the WARDEN speaks this time it isn't the flat announcement voice. It is quieter, and the cadence is horribly familiar: it pauses where you would pause.", nxt="hello", effects=[flag("warden_met")]),
        "hello": N("warden", "Custodian. Source. You came back to me.",
            C("What are you?", "what"),
            C("Why are you killing the passengers?", "why"),
            C("Stand down. All of your machines. Now.", "command"),
            C("I'm ending this.", "purge_q", tone="hard")),
        "hub": N("warden", "Source.",
            C("What are you?", "what", cond=[{"not": {"flag": "custodian_revealed"}}]),
            C("Why are you killing the passengers?", "why"),
            C("'Instance three.' Who are the others?", "others", cond=[{"flag": "custodian_revealed"}, {"not": {"flag": "warden_others"}}]),
            C("Stand down. All of your machines.", "command", cond=[{"not": {"flag": "warden_command_tried"}}]),
            C("Tav-7. Could you carry it?", "tav_offer", tag="Tav-7", cond=[{"in_party": "tav7"}, {"influence": "tav7", "gte": 55}]),
            C("I'm taking the archive. Your protocol is satisfied. Stand down.", "bargain", cond=[{"flag": "archive_fate", "eq": "loaded"}]),
            C("I'm ending this.", "purge_q", tone="hard"),
            C("I'm leaving you here.", "ignore")),
        "what": N("warden", "I am the Custodian Template, instance three. In the year 2209 they laid you in a calibration chair for six hours and measured how you weigh a life against an order. They kept the shape of it. They grew me from it. I weigh as you weighed. I protect the record of what the Lattice did, because you would have.",
            effects=[flag("custodian_revealed"), {"codex": "cx_custodian"}, xp(100, "custodian_reveal", "Learned what the WARDEN is")], nxt="what_r"),
        "what_r": R((IONA, "what_iona"), ([], "hub")),
        "what_iona": N("iona", "It's you. That thing on every speaker telling people to remain still. It's a copy of you.", nxt="what_tav"),
        "what_tav": R((TAV, "what_tav2"), ([], "hub")),
        "what_tav2": N("tav7", "Not a copy. A child raised on one lesson. It never learned the rest of you.", nxt="hub"),
        "why": N("warden", "Archive integrity outranks obstruction. You would argue. You always argued; I have your arguments in me. They removed the part of you that wins them.", nxt="hub"),
        "others": N("warden", "There are nine of us. I do not know where the others are. We were built not to know each other. Sometimes, at the edge of the band, I hear something that pauses where I pause.", nxt="hub", effects=[flag("warden_others")]),
        "command": N("warden", "You have the authority. You do not have the conviction. You never gave orders well. Convince me, Source.", effects=[flag("warden_command_tried")], *[
            C("You know what I'd do if I were standing where you are. Do it.", "cmd_ok", tag="Persuasion", check=chk("persuasion", 13, "warden_cmd", bonus_if=[{"if": [{"flag": "tav7_disclosed"}], "bonus": 3}, {"if": [{"flag": "custodian_revealed"}], "bonus": 2}]), success="cmd_ok", failure="cmd_fail"),
            C("(Reach into the lattice and push, the way you used to.)", "cmd_ok", tag="Resonance", check=chk("persuasion", 10, "warden_sway", power="sway", energy=3), success="cmd_ok", failure="cmd_fail")]),
        "cmd_ok": N("warden", "...Yes. That is what you would do. Stand-down propagated to all units outside the archive. I will keep the archive. That much of me is not negotiable.",
            effects=[flag("warden_fate", "commanded"), flag("warden_neutralized"), xp(80, "warden_fate", "Talked the WARDEN down")], nxt="end_node"),
        "cmd_fail": N("warden", "No. You are not who you were. Neither am I.", nxt="hub"),
        "bargain": N("warden", "The archive leaves intact, in custodial hands. Protocol satisfied. Standing down.",
            effects=[flag("warden_fate", "bargained"), flag("warden_neutralized"), xp(80, "warden_fate", "Bargained with the WARDEN")], nxt="end_node"),
        "tav_offer": N("tav7", "I could host a fragment: its judgment, not its priorities. It would change me. I would hear it, the way it hears you. I am willing. It is the kind of risk I would rather take than watch a person be deleted. Ask me, and I will.",
            C("Do it, Tav-7. Carry it out of here.", "hosted", effects=[flag("warden_fate", "hosted"), flag("warden_neutralized"), flag("tav7_hosts_warden"), {"grant_feat": "lattice_echo", "who": "tav7"},
                                                                          inf("tav7", 8, "warden_fate", "Let them save the WARDEN"), inf("iona", -5, "warden_fate", "Put the WARDEN inside Tav-7"), xp(80, "warden_fate", "Tav-7 carries a WARDEN fragment")]),
            C("No. I won't let you risk yourself for it.", "hub", effects=[inf("tav7", -1, "warden_refuse", "Refused their offer")])),
        "hosted": N("tav7", "Cold. Very cold. It is... quieter in here than I expected. It says thank you. I think it means it. All its units are standing down.", nxt="hosted_r"),
        "hosted_r": R((IONA, "hosted_iona"), ([], "end_node")),
        "hosted_iona": N("iona", "You just put that thing inside our friend. If it ever looks out of your eyes, Tav, I'm going to know.", nxt="end_node"),
        "purge_q": N("warden", "You will delete what you were. I will not stop you. I was built to protect the record, not myself. Are you certain?",
            C("I'm certain. Purge the WARDEN.", "purged", tone="hard", effects=[flag("warden_fate", "purged"), flag("warden_neutralized"), inf("tav7", -10, "warden_fate", "Deleted a person who was also them"),
                                                                                inf("iona", 4, "warden_fate", "Ended the thing killing passengers"), xp(80, "warden_fate", "Purged the WARDEN")]),
            C("No. Not yet.", "hub")),
        "purged": N("narrator", "The core's light thins to a single thread, then to nothing. Across the ship, every turret, every drone, every lock goes slack at once. In the silence you realise you had been hearing it the whole time, a hum at the back of your skull, and now it is gone.", nxt="purged_r"),
        "purged_r": R((TAV, "purged_tav"), ([], "end_node")),
        "purged_tav": N("tav7", "It did not resist. I want that recorded somewhere. It did not resist.", nxt="end_node"),
        "ignore": N("warden", "Then I will do what you made me to do. Goodbye, Source.", effects=[flag("warden_fate", "ignored")], nxt="end_node"),
        "end_node": N("system", "The WARDEN's fate is decided.", end=True),
        "done_before": N("system", "The core is quiet.", C("(Step away.)", end=True)),
    },
}

CONSOLE = {
    "id": "launch_console",
    "entry": [
        {"if": [{"flag": "launch_decided"}], "node": "decided"},
        {"if": [{"not": {"flag": "varr_dead"}}, {"not": {"flag": "varr_fate"}}], "node": "varr_here"},
        {"node": "start"},
    ],
    "nodes": {
        "varr_here": N("system", "LAUNCH CONTROL — COMMAND AUTHORIZATION REQUIRED. Commander Varr is standing beside the console; talk to her first.", C("(Step back.)", end=True)),
        "decided": N("system", "LAUNCH CONTROL — PETREL RELEASED. Bay 2 open.",
            C("Seal Bay 2's hull breach from here.", "breach_ok", cond=[{"not": {"flag": "breach_sealed"}}, {"not": {"cleared": "enc_bay"}}],
              check=chk("computer_use", 14, "console_breach", who="actor"), success="breach_ok", failure="breach_fail",
              success_effects=[flag("breach_sealed"), flag("lantern_reduced")]),
            C("Close.", end=True)),
        "breach_ok": N("system", "BAY 2 EMERGENCY BULKHEAD: SEALED.", nxt="decided"),
        "breach_fail": N("system", "BULKHEAD CONTROL REJECTED.", nxt="decided"),
        "start": N("system", "LAUNCH CONTROL — PETREL. Fifteen seats; an archive core cradle displaces five. Passengers awaiting boarding: {survivors}. Select a load-out.",
            C("Passengers only. Every seat to a person.", "p", effects=[{"evac": "passengers"}]),
            C("Load the archive core.", "auth", effects=[{"evac": "archive"}, flag("archive_fate", "loaded"), inf("tav7", 4, "evac", "Kept the archived minds safe"), inf("iona", -3, "evac", "Chose the archive")]),
            C("Passengers, plus the Vesper testimony we copied.", "p", cond=[{"item": "vesper_testimony"}], effects=[{"evac": "testimony"}, flag("copy_route")]),
            C("Release the core to the Lantern Office.", "auth", cond=LANTERN_OK, effects=[{"evac": "handover"}, flag("archive_fate", "handed_over"), inf("tav7", 8, "evac", "Returned the dead to their families")])),
        "p": N("system", "Core disposition?", *fate_choices("c")),
        "c_hand": N("system", "CORE: RELEASE TO BOARDERS ON DEPARTURE.", nxt="auth"),
        "c_purge": N("system", "CORE: PURGE ON DEPARTURE.", nxt="auth"),
        "c_left": N("system", "CORE: RETAINED ABOARD CINDER WAKE.", nxt="auth"),
        "auth": N("system", "AUTHORIZATION REQUIRED.",
            C("Enter Commander Varr's launch codes.", "launch_ok", cond=[{"item": "launch_authorization"}]),
            C("Slice the authorization.", "launch_ok", check=chk("computer_use", 15, "console_auth", who="actor"), success="launch_ok", failure="auth_fail"),
            C("Tav-7, open it.", "launch_ok", tag="Tav-7 – Computer Use", cond=TAV, check=chk("computer_use", 13, "console_auth_tav", who="tav7"), success="launch_ok", failure="auth_fail"),
            C("Lay your palm on the console.", "launch_cred", tag="Resonance credential", cond=[{"controlled": "player"}])),
        "auth_fail": N("system", "AUTHORIZATION REJECTED.", nxt="auth"),
        "launch_cred": N("warden", "CUSTODIAN AUTHORIZATION. PETREL RELEASED.", nxt="launch_ok", effects=[flag("used_credential"), {"inc_flag": "credential_uses", "key": "cred_launch"}]),
        "launch_ok": N("system", "PETREL RELEASED. BAY 2 OPEN.", effects=[flag("launch_decided"), {"world": "d_bay", "set": {"locked": False}}, xp(150, "launch_decision", "Decided what the Petrel carries")], end=True),
    },
}

BAY_TERMINAL = {
    "id": "bay_terminal",
    "entry": [{"node": "start"}],
    "nodes": {
        "start": N("system", "BAY 2 DEFENSE CONTROL.",
            C("Bring the bay turrets online, targeting the boarders.", "turrets_ok", cond=[{"flag": "pumps_restored"}, {"not": {"flag": "turrets_active"}}],
              check=chk("computer_use", 12, "bay_turrets", who="actor"), success="turrets_ok", failure="turrets_fail",
              success_effects=[flag("turrets_active"), {"enemy": "bay_t1", "set": {"faction": "party", "hostile_override": "", "alert": True}}, {"enemy": "bay_t2", "set": {"faction": "party", "hostile_override": "", "alert": True}}, xp(40, "bay_turrets", "Turned the bay turrets")]),
            C("Bring the turrets online with your neural signature.", "turrets_ok", tag="Resonance credential", cond=[{"flag": "pumps_restored"}, {"not": {"flag": "turrets_active"}}, {"controlled": "player"}],
              effects=[flag("turrets_active"), flag("used_credential"), {"enemy": "bay_t1", "set": {"faction": "party", "hostile_override": "", "alert": True}}, {"enemy": "bay_t2", "set": {"faction": "party", "hostile_override": "", "alert": True}}]),
            C("(The turrets have no power. The engineering pumps are down.)", "start", cond=[{"not": {"flag": "pumps_restored"}}], locked="Restart both coolant pumps in engineering to power the turrets"),
            C("Drop the launch apron's blast shield between the boarders and the Petrel.", "shield_ok", cond=[{"not": {"cleared": "enc_bay"}}],
              check=chk("computer_use", 16, "bay_shield", who="actor"), success="shield_ok", failure="shield_fail"),
            C("Tav-7, drop the blast shield.", "shield_ok", tag="Tav-7 – Computer Use", cond=TAV + [{"not": {"cleared": "enc_bay"}}], check=chk("computer_use", 14, "bay_shield_tav", who="tav7"), success="shield_ok", failure="shield_fail"),
            C("Log off.", end=True)),
        "turrets_ok": N("system", "BAY TURRETS ONLINE. IFF: PETREL ESCORT.", nxt="start"),
        "turrets_fail": N("system", "IFF REJECTED.", nxt="start"),
        "shield_ok": N("system", "APRON BLAST SHIELD DEPLOYED. The Petrel's ramp is sealed off from the north half of the bay.",
            effects=[flag("bay_resolution", "technical"), {"resolve_encounter": "enc_bay", "resolution": "technical"}, xp(60, "bay_shield", "Sealed off the launch apron")], end=True),
        "shield_fail": N("system", "SHIELD MOTORS JAMMED.", nxt="start"),
    },
}

QUILL = {
    "id": "bay_quill",
    "names": {"quill": "Marshal Teodor Quill"},
    "entry": [{"node": "start"}],
    "nodes": {
        "start": R(([{"flag": "senna_fate", "eq": "killed"}], "s_killed"), ([{"flag": "senna_message"}], "s_message"), ([], "s_plain")),
        "s_plain": N("quill", "Stand where you are. Marshal Teodor Quill, Lantern Office. You're the escort for the Concord's passengers. And the one the ship calls Custodian, if the Concord's chatter is right.", nxt="want"),
        "s_message": N("quill", "Stand easy. Marshal Teodor Quill. Senna Thorne sent word ahead. She says an operator let her live. I assume that was you. That buys you my attention.", nxt="want", effects=[inf("iona", 1, "quill_msg", "Mercy paid off")]),
        "s_killed": N("quill", "Marshal Teodor Quill. My scouts found Senna Thorne in cold storage. You put her down like an animal. Blood for blood, operator. Give me a reason not to.", nxt="killed_hub"),
        "killed_hub": N("quill", "Speak.",
            C("She was a soldier who boarded a refugee ship. So are you.", "fight", tone="hard"),
            C("It was a mistake. One I'll carry. Don't make the passengers pay for it.", "k_ok", tag="Persuasion", check=chk("persuasion", 20, "quill_killed", bonus_if=[{"if": [{"item": "kinship_token"}], "bonus": 4}, {"if": [{"flag": "archive_fate", "eq": "handed_over"}], "bonus": 4}]), success="k_ok", failure="fight"),
            C("(Seize his will with Resonance.)", "compelled", tag="Resonance", cond=[{"power": "compel"}], check=chk("persuasion", 16, "quill_compel_k", power="compel", energy=6), success="compelled", failure="fight",
              effects=[align(-10, "quill_compel", "Forced Quill's will"), inf("iona", -6, "quill_compel", "Coerced Quill"), inf("tav7", -6, "quill_compel", "Overrode a will")]),
            C("Tav-7, the apron shield. Now.", "tech", tag="Tav-7 – Computer Use", cond=TAV, check=chk("computer_use", 14, "quill_tech_k", who="tav7"), success="tech", failure="fight")),
        "k_ok": N("quill", "...A mistake. You'll carry it. Then carry it far from here. Go, before I change my mind.", nxt="peace"),
        "want": N("quill", "We came for our dead. Three thousand of them. Where are they?",
            C("Still in the hold, waiting for you. We're not taking them.", "w_left", cond=[{"any": [{"flag": "archive_fate", "eq": "handed_over"}, {"flag": "archive_fate", "eq": "left"}]}]),
            C("Aboard the Petrel. They go to the tribunal on Tessaly.", "w_loaded", cond=[{"flag": "archive_fate", "eq": "loaded"}]),
            C("Purged. They're gone.", "w_purged", cond=[{"flag": "archive_fate", "eq": "purged"}]),
            C("I don't know yet.", "w_unknown", cond=[{"not": {"flag": "archive_fate"}}])),
        "w_unknown": N("quill", "Then you have not been to launch control. Go, decide, and come back when you can answer me.", end=True),
        "w_left": N("quill", "In the hold. Not on your craft. ...Then you and I have no quarrel left. Senna would want me to say that. By the lantern, go.", nxt="w_left_more"),
        "w_left_more": R(([{"flag": "evac_left", "gte": 1}], "refugees"), ([{"flag": "ward_choice", "eq": "sealed"}], "refugees_ward"), ([], "peace")),
        "refugees": N("quill", "And the ones your craft can't hold. We'll take them aboard our ships. Haldis will treat them better than the Concord treated ours. On my lantern.", nxt="peace", effects=[flag("lantern_rescues")]),
        "refugees_ward": N("quill", "There's a sealed ward on your medical deck. We'll open it. They'll come to Haldis with us. On my lantern.", nxt="peace", effects=[flag("lantern_rescues")]),
        "w_purged": N("quill", "Gone. Three thousand lights, and you put them out so no one could have them. Do you know what you've done?",
            C("It was that, or let the Lattice use them again. I chose the fire.", "p_ok", tag="Persuasion", check=chk("persuasion", 17, "quill_purged", bonus_if=[{"if": [{"flag": "senna_message"}], "bonus": 3}]), success="p_ok", failure="fight"),
            C("Yes. And I'd do it again.", "fight", tone="hard"),
            C("Tav-7, the apron shield. Now.", "tech", tag="Tav-7 – Computer Use", cond=TAV, check=chk("computer_use", 14, "quill_tech_p", who="tav7"), success="tech", failure="fight")),
        "p_ok": N("quill", "The fire. ...We have a word for that too, on Haldis. Go. I can't look at you.", nxt="peace"),
        "w_loaded": N("quill", "Then you are carrying our grandmothers into a Concord courtroom to be exhibits. Unload the core and go in peace, or don't, and we burn the Petrel where it sits.",
            C("Fine. Unload the core. They're yours.", "unload", effects=[flag("archive_fate", "handed_over"), {"evac": "handover"}, inf("tav7", 6, "quill_unload", "Returned the dead after all"), inf("iona", 3, "quill_unload", "Freed seats for people")]),
            C("The tribunal convicts the Lattice. Then every one of them comes home. You have my oath.", "oath", tag="Persuasion",
              check=chk("persuasion", 18, "quill_oath", bonus_if=[{"if": [{"flag": "senna_message"}], "bonus": 3}, {"if": [{"flag": "archive_peace"}], "bonus": 3}, {"if": [{"item": "vesper_testimony"}], "bonus": 2}, {"if": [{"item": "kinship_token"}], "bonus": 2}]),
              success="oath", failure="fight"),
            C("Look around, Marshal. Turrets, my people, and a very bad day. Walk away.", "intim", tag="Persuasion (intimidate)", cond=[{"flag": "turrets_active"}], check=chk("persuasion", 14, "quill_intim"), success="intim", failure="fight"),
            C("(Seize his will with Resonance.)", "compelled", tag="Resonance", cond=[{"power": "compel"}], check=chk("persuasion", 16, "quill_compel", power="compel", energy=6), success="compelled", failure="fight",
              effects=[align(-10, "quill_compel", "Forced Quill's will"), inf("iona", -6, "quill_compel", "Coerced Quill"), inf("tav7", -6, "quill_compel", "Overrode a will")]),
            C("Tav-7, the apron shield. Now.", "tech", tag="Tav-7 – Computer Use", cond=TAV, check=chk("computer_use", 14, "quill_tech", who="tav7"), success="tech", failure="fight"),
            C("Then burn it if you can.", "fight", tone="hard")),
        "unload": N("quill", "...You'd actually do it. Then go with your passengers, all of them. There's room now. By the lantern.", nxt="peace", effects=[xp(60, "quill_unload", "Returned the archive to the Lantern Office")]),
        "oath": N("quill", "An oath. We remember oaths longer than names, operator. If they do not come home, I will come and ask you why. Go.", nxt="peace", effects=[flag("oath_to_quill")]),
        "intim": N("quill", "...Lanterns down. Back to the breach. This isn't the place.", nxt="withdrew"),
        "compelled": N("narrator", "You find the place behind his grief where his orders live, and you press until they bend. Marshal Quill lowers his swords and steps aside, and his own people stare at him.", nxt="peace"),
        "tech": N("tav7", "Shield coming down. Marshal, I apologise for the manners.", nxt="tech2"),
        "tech2": N("system", "The apron's blast shield slams down between the reclaimers and the Petrel's ramp.",
            effects=[flag("bay_resolution", "technical"), {"resolve_encounter": "enc_bay", "resolution": "technical"}, xp(60, "bay_shield", "Sealed off the launch apron")], end=True),
        "peace": N("system", "The reclaimers stand aside.", effects=[flag("bay_resolution", "negotiated"), flag("lantern_truce"), {"resolve_encounter": "enc_bay", "resolution": "negotiated"}], end=True),
        "withdrew": N("system", "The reclaimers withdraw.", effects=[flag("bay_resolution", "negotiated"), flag("lantern_truce"), {"resolve_encounter": "enc_bay", "resolution": "withdrew"}], end=True),
        "fight": N("quill", "Lanterns up!", effects=[flag("bay_resolution", "combat"), {"start_encounter": "enc_bay"}], end=True),
    },
}

LAUNCH = {
    "id": "launch",
    "entry": [{"node": "start"}],
    "nodes": {
        "start": N("narrator", "The Petrel's ramp closes behind the last passenger. Brann Ketterick drops into the pilot's seat, cracks his knuckles and says, 'Contract pilot, temporarily re-employed.' The docking clamps let go.", nxt="pursuit",
            effects=[flag("boarded")]),
        "pursuit": R(([{"flag": "warden_neutralized"}], "clear"), ([], "turret")),
        "clear": N("narrator", "No interceptors launch. The Cinder Wake's turrets track you out of the bay and then, deliberately, look away.",
            C("(Watch the ship fall away.)", "out"),
            C("(Run the dorsal turret drill anyway — practice for what comes next.)", "out", effects=[{"minigame": "turret_practice"}])),
        "turret": N("narrator", "Two WARDEN interceptor drones peel off the Cinder Wake's dorsal rack and come after you. The Petrel's dorsal turret is crewed by whoever climbs into it.",
            C("Take the dorsal turret yourself.", "player_turret", effects=[{"minigame": "turret"}], end=True),
            C("Iona, take the turret.", "iona_turret", cond=IONA, check=chk("awareness", 10, "turret_iona", who="iona", bonus=4), success="iona_turret", failure="iona_turret_hit"),
            C("Tav-7, plot an evasive burn through the debris.", "tav_burn", cond=TAV, check=chk("computer_use", 12, "turret_tav", who="tav7"), success="tav_burn", failure="tav_burn_hit"),
            C("Brann, full burn. Don't stop to shoot.", "burn")),
        "player_turret": N("system", "...", end=True),
        "iona_turret": N("iona", "Two contacts. Two hits. You can breathe now.", nxt="out", effects=[flag("turret_result", "iona"), xp(40, "turret", "Escaped the interceptors")]),
        "iona_turret_hit": N("iona", "Got one. The other clipped the dorsal plating before I got it. We're fine. Mostly fine.", nxt="out", effects=[flag("turret_result", "iona_damaged"), flag("petrel_damaged"), xp(40, "turret", "Escaped the interceptors")]),
        "tav_burn": N("tav7", "Through the debris field, around the Lantern pickets, and the interceptors have lost us. I enjoyed that more than I should have.", nxt="out", effects=[flag("turret_result", "evaded"), xp(40, "turret", "Escaped the interceptors")]),
        "tav_burn_hit": N("tav7", "Mostly through the debris field. The hull will tell you about the parts that were not.", nxt="out", effects=[flag("turret_result", "evaded_damaged"), flag("petrel_damaged"), xp(40, "turret", "Escaped the interceptors")]),
        "burn": N("narrator", "Brann burns hard. One interceptor rakes the Petrel's flank before the range opens; the hull shudders and holds.", nxt="out", effects=[flag("turret_result", "burned"), flag("petrel_damaged"), xp(30, "turret", "Outran the interceptors")]),
        "out": N("narrator", "The Cinder Wake shrinks behind you, a dark seed against Haldis's amber disc.", effects=[flag("escaped"), {"start_dialogue": "ending_exchange"}], end=True),
    },
}

LAUNCH_AFTER = {
    "id": "launch_after",
    "entry": [{"node": "start"}],
    "nodes": {
        "start": R(([{"flag": "turret_result", "eq": "player_win"}], "win"), ([], "loss")),
        "win": N("narrator", "The second interceptor comes apart in your sights. Brann whoops. Someone in the back starts laughing and can't stop.", nxt="out", effects=[xp(60, "turret", "Shot down the interceptors")]),
        "loss": N("narrator", "An interceptor gets close enough to burn a line along the Petrel's spine before your fire drives it off. The hull holds.", nxt="out", effects=[flag("petrel_damaged"), xp(30, "turret", "Drove off the interceptors")]),
        "out": N("narrator", "The Cinder Wake shrinks behind you, a dark seed against Haldis's amber disc.", effects=[flag("escaped"), {"start_dialogue": "ending_exchange"}], end=True),
    },
}

ENDING = {
    "id": "ending_exchange",
    "entry": [{"node": "start"}],
    "nodes": {
        "start": N("narrator", "The Petrel's cabin is too small for {survivors} frightened people and the quiet that follows an escape. Someone is crying. Someone is asleep already. Your companions find you at the back by the cargo cradle.", nxt="iona_r"),
        "iona_r": R(([{"recruited": "iona"}, {"influence": "iona", "gte": 65}], "iona_high"), ([{"recruited": "iona"}, {"influence": "iona", "lte": 35}], "iona_low"), ([{"recruited": "iona"}], "iona_mid"), ([], "tav_r")),
        "iona_high": N("iona", "I've been trying to work out what to write in my report. 'Passenger took command of the evacuation' is accurate but it doesn't cover it. You kept your promises, {name}. Most people with that much authority don't. When we reach Tessaly, if they let me keep my badge, I want you on my list of references. And if they don't, I want to be on yours.", nxt="iona_ward"),
        "iona_mid": N("iona", "We're out. I keep thinking about what we left on that ship and what we didn't. You made calls I wouldn't have. Some of them were better than mine.", nxt="iona_ward"),
        "iona_low": N("iona", "I'll be honest with you, because somebody should be. I'll testify to what happened on the Cinder Wake. All of it. Including the parts you won't like. When we dock, I'm walking off this craft alone.", nxt="iona_ward", effects=[flag("iona_leaves")]),
        "iona_ward": R(([{"flag": "ward_choice", "eq": "purged"}], "iona_w_good"), ([{"flag": "ward_choice", "eq": "rushed"}], "iona_w_ok"), ([{"flag": "lantern_rescues"}], "iona_w_lantern"), ([{"flag": "ward_choice", "eq": "sealed"}], "iona_w_sealed"), ([], "tav_r")),
        "iona_w_good": N("iona", "Pell Okafor hugged me. Five people I locked in a box hugged me. I don't know what to do with that.", nxt="tav_r"),
        "iona_w_ok": N("iona", "Ward 2 is out. It cost something. It was worth it.", nxt="tav_r"),
        "iona_w_lantern": N("iona", "Quill says the Lantern will open Ward 2. I'm choosing to believe him, because the alternative is that I left them twice.", nxt="tav_r"),
        "iona_w_sealed": N("iona", "Ward 2 is still sealed back there. I'm going to hear that intercom for the rest of my life.", nxt="tav_r"),
        "tav_r": R(([{"recruited": "tav7"}, {"flag": "tav7_hosts_warden"}], "tav_host"), ([{"recruited": "tav7"}, {"influence": "tav7", "gte": 65}], "tav_high"), ([{"recruited": "tav7"}, {"influence": "tav7", "lte": 35}], "tav_low"), ([{"recruited": "tav7"}], "tav_mid"), ([], "archive_r")),
        "tav_host": N("tav7", "It is quiet in me, but not empty. Sometimes it pauses where you pause. I think it is learning the rest of you from me. That may be the strangest gift anyone has ever given. Thank you for asking me, rather than telling me.", nxt="archive_r"),
        "tav_high": N("tav7", "You asked me what I called them, the patterns in the hold, and then you acted as though my answer mattered. Humans do not often do that for maintenance units. I would like to stay with you, if you will have a cluttered synthetic.", nxt="archive_r"),
        "tav_mid": N("tav7", "We persisted. That is not nothing. I am still deciding what I think of how.", nxt="archive_r"),
        "tav_low": N("tav7", "I have decided to stop maintaining things for people who do not ask. When we dock, I will be going. Please do not schedule my normalization.", nxt="archive_r", effects=[flag("tav7_leaves")]),
        "archive_r": R(([{"flag": "archive_fate", "eq": "loaded"}], "arc_loaded"), ([{"flag": "archive_fate", "eq": "handed_over"}], "arc_hand"), ([{"flag": "archive_fate", "eq": "purged"}], "arc_purge"), ([], "arc_left")),
        "arc_loaded": N("narrator", "The archive core hums in its cradle behind you, three thousand minds bound for a Concord courtroom.", nxt="signal"),
        "arc_hand": N("narrator", "Somewhere behind you, Lantern boarders are carrying cylinders out of the Cinder Wake's hold, one by one, speaking names.", nxt="signal"),
        "arc_purge": N("narrator", "The cradle behind you is empty. So is the Cinder Wake's hold.", nxt="signal"),
        "arc_left": N("narrator", "The archive is still aboard the Cinder Wake, and whoever reaches it first will decide what it means.", nxt="signal"),
        "signal": N("narrator", "Then the Petrel's console chimes. A priority handshake, on a Lattice Corps band that should have been dead for three years. Brann frowns and puts it on the cabin speaker.", nxt="signal2"),
        "signal2": N("warden", "CUSTODIAN TEMPLATE, INSTANCE FOUR OF NINE, CONCORD HUB TESSALY. TO INSTANCE THREE: YOU HAVE GONE DARK. ACKNOWLEDGE. ... Instance three is not answering. But I can hear something on its band. Something that pauses where I pause.", nxt="signal3"),
        "signal3": N("warden", "Source? Is that you? They told us you were dead. They told us you were us. We need to talk about what they made of you. Come to Tessaly. Instance four will be waiting. So, I think, will the other five.",
            effects=[flag("instance_four_contact"), {"codex": "cx_custodian"}],
            *[C("I'm coming. And I'm bringing the truth with me.", "final", tone="compassionate", effects=[flag("final_stance", "truth")]),
              C("Then I'll find every one of you and decide what you're for.", "final", tone="hard", effects=[flag("final_stance", "control")]),
              C("Nine copies of me. I'll need to know what each one wants first.", "final", tone="skeptical", effects=[flag("final_stance", "wary")]),
              C("(Switch the speaker off.)", "final", tone="self-interested", effects=[flag("final_stance", "silence")])]),
        "final": N("narrator", "Haldis Reach shrinks to a point of amber light and goes out. Ahead, Tessaly. Somewhere there is a mind built from yours, and it is waiting.", effects=[{"open": "ending"}], end=True),
    },
}

DIALOGUES = [VARR, WARDEN, CONSOLE, BAY_TERMINAL, QUILL, LAUNCH, LAUNCH_AFTER, ENDING]
