# Companion conversations (Party screen → Talk, or at muster points). Repeatable
# hubs; influence-gated topics, one-time effects keyed so they cannot be farmed.

IONA_TALK = {
    "id": "iona_talk",
    "names": {"iona": "Iona Rell"},
    "entry": [
        {"if": [{"influence": "iona", "lte": 35}, {"not": {"flag": "iona_low_done"}}], "node": "low"},
        {"node": "hub"},
    ],
    "nodes": {
        "hub": N("iona", "You want something, or are you checking I'm still upright?",
            C("How are you holding up?", "holding"),
            C("About Ward 2...", "ward", cond=[{"flag": "ward_decided"}, {"not": {"flag": "iona_ward_talk"}}]),
            C("Why ship's security? You could have been anywhere.", "past", cond=[{"influence": "iona", "gte": 65}], hide=[{"flag": "iona_past_done"}], tag="Trust", locked="Iona doesn't trust you with that yet (influence 65+)"),
            C("You've seen me use Resonance. Do you feel anything, when I do?", "train", cond=[{"influence": "iona", "gte": 70}, {"flag": "iona_res_seen"}, {"not": {"flag": "iona_trained"}}], tag="Resonance training"),
            C("You've seen what I can do. Ever wonder about it?", "res_seen", cond=[{"not": {"flag": "iona_res_seen"}}, {"any": [{"flag": "used_credential"}, {"flag": "custodian_revealed"}]}]),
            C("Never mind.", end=True)),
        "holding": R(([{"influence": "iona", "gte": 65}], "hold_high"), ([{"influence": "iona", "lte": 35}], "hold_low"), ([], "hold_mid")),
        "hold_high": N("iona", "Better than I should be. Working with you helps. Don't let it go to your head.", nxt="hub"),
        "hold_mid": N("iona", "Upright. Annoyed. Mostly upright.", nxt="hub"),
        "hold_low": N("iona", "Fine. Ask me later.", end=True),
        "ward": R(([{"flag": "ward_choice", "eq": "purged"}], "ward_good"), ([{"flag": "ward_choice", "eq": "rushed"}], "ward_rush"), ([], "ward_bad")),
        "ward_good": N("iona", "I keep replaying the moment the seal opened. Thank you. You let me be the one to undo it.", nxt="hub", effects=[flag("iona_ward_talk")]),
        "ward_rush": N("iona", "We got them out. It cost someone in triage. I'd make the same choice. I hate that I'd make the same choice.", nxt="hub", effects=[flag("iona_ward_talk")]),
        "ward_bad": N("iona", "Don't. I know why you did it. I did it first. I don't need to talk about it to keep carrying it.", nxt="hub", effects=[flag("iona_ward_talk")]),
        "past": N("iona", "Tessaly security service, ten years. A governor ordered us to clear a strike line with stun batons. I refused. They didn't fire me; they transferred me to a refugee ship and called it mercy. When Varr told me to seal Ward 2, I thought: last time I refused, someone else just did it worse. So I did it myself. That's the story.",
            C("Refusing that order was right. Sealing the ward wasn't. You know the difference better than anyone.", "past2", effects=[inf("iona", 3, "past", "Respected her refusal")]),
            C("You did what kept the most people alive. That's the job.", "past2"),
            C("Everyone follows orders, eventually.", "past2", tone="hard", effects=[inf("iona", -2, "past", "Dismissed her story")])),
        "past2": N("iona", "Here's something I haven't told you. Varr's launch codes are split authority: command plus the senior security officer. That's me. If she won't release the Petrel, I can. And here: something they teach security on Tessaly. Fire so they keep their heads down; don't fire to kill. Covering fire. It'll keep you alive.",
            effects=[flag("iona_past_done"), flag("iona_can_authorize"), {"grant_feat": "covering_fire", "who": "iona"}, xp(50, "iona_past", "Iona trusts you with her story")], nxt="hub"),
        "res_seen": N("iona", "Wonder? It scares me a little. It also... when you opened that door, I felt it. Like a pressure behind my eyes. I've never told anyone I feel things like that.", nxt="hub", effects=[flag("iona_res_seen")]),
        "train": N("iona", "Every time. Like hearing music through a wall. Are you saying I could learn it?",
            C("Lattice screening missed people all the time. Close your eyes. Find the pressure. Breathe into it.", "train_ok"),
            C("Not now. It's dangerous to learn in a crisis.", "hub")),
        "train_ok": N("narrator", "You talk her through the first exercise the Lattice ever taught you: find the hum, don't fight it, follow it. Iona's breath catches. A faint warmth gathers around her hands, and the cut on her knuckle closes as you watch.",
            effects=[flag("iona_trained"), {"grant_feat": "resonance_sensitive", "who": "iona"}, {"grant_power": "mend", "who": "iona"}, {"grant_power": "echo_sense", "who": "iona"},
                     inf("iona", 5, "train", "Taught her Resonance"), xp(100, "iona_train", "Awakened Iona's Resonance")], nxt="train2"),
        "train2": N("iona", "...That was me. That was actually me. I'm going to need a minute. And then I'm going to need you to teach me everything.", nxt="hub"),
        "low": N("iona", "We need to talk. I don't trust your judgment. I've watched you make calls I'd file a report on. Give me a reason to keep following you.",
            C("You're right to push back. I've made calls I'm not proud of. Keep pushing.", "low_ok", tag="Persuasion", check=chk("persuasion", 14, "iona_low"), success="low_ok", failure="low_fail"),
            C("Because I'm the one getting people off this ship.", "low_fail"),
            C("Follow me or don't. Your choice.", "low_fail", tone="hard")),
        "low_ok": N("iona", "...All right. I'll keep pushing. You keep listening.", effects=[flag("iona_low_done"), inf("iona", 8, "low_talk", "Heard her objections")], nxt="hub"),
        "low_fail": N("iona", "Then I'll stay as far as the bay, because the passengers need me. After that, we're done.", effects=[flag("iona_low_done"), flag("iona_distrust")], end=True),
    },
}

TAV_TALK = {
    "id": "tav7_talk",
    "names": {"tav7": "Tav-7"},
    "entry": [
        {"if": [{"influence": "tav7", "lte": 35}, {"not": {"flag": "tav_low_done"}}], "node": "low"},
        {"node": "hub"},
    ],
    "nodes": {
        "hub": N("tav7", "Yes? I have spare cycles. I have, in fact, mostly spare cycles. It is a strange day.",
            C("How are you holding up?", "holding"),
            C("What will you do, after?", "after"),
            C("Is there something you haven't told me?", "secret", cond=[{"influence": "tav7", "gte": 65}], hide=[{"flag": "tav_secret_done"}], tag="Trust", locked="Tav-7 isn't ready to share that (influence 65+)"),
            C("The WARDEN said it hears things that pause where it pauses. Do you hear it?", "warden", cond=[{"flag": "tav7_marked"}, {"not": {"flag": "tav_warden_talk"}}]),
            C("Never mind.", end=True)),
        "holding": R(([{"influence": "tav7", "gte": 65}], "h_high"), ([], "h_mid")),
        "h_high": N("tav7", "I am well. I find I like being asked.", nxt="hub"),
        "h_mid": N("tav7", "Operational. That is a joke. I am practising.", nxt="hub"),
        "after": N("tav7", "Tessaly has a court that hears synthetic personhood claims. Nobody has ever won one. I would like to be the first, or at least the second.", nxt="hub"),
        "secret": N("tav7", "Yes. Eleven crew died on the Cinder Wake today, near maintenance terminals. I copied what I could reach of their patterns into my own storage before they decayed. I did not ask. They could not answer. I have been carrying them, and I am not certain it was right.",
            C("You preserved them. That's what you believe in. I'm glad you did it.", "s_approve", effects=[inf("tav7", 4, "secret", "Approved of their choice")]),
            C("You took people without their consent. That's what the Lattice did.", "s_disapprove", effects=[inf("tav7", -2, "secret", "Called it what it was")]),
            C("That's yours to decide. When we land, ask their families.", "s_neutral", effects=[inf("tav7", 2, "secret", "Left the choice to them")])),
        "s_approve": N("tav7", "Thank you.", nxt="s_after"),
        "s_disapprove": N("tav7", "...Yes. That is the risk I took. I will ask their families. I will accept their answers.", nxt="s_after"),
        "s_neutral": N("tav7", "I will. That is a good answer.", nxt="s_after"),
        "s_after": N("tav7", "Since I am telling secrets: the WARDEN listens for your voice before it listens for its own priorities. Speak to it as yourself, not as a commander, and it will hear you. And I have learned to run my chassis hotter than its rating. Watch.",
            effects=[flag("tav_secret_done"), flag("tav7_disclosed"), {"grant_feat": "overclock", "who": "tav7"}, xp(50, "tav_secret", "Tav-7 shared their secret")], nxt="hub"),
        "warden": N("tav7", "Since I broke its lock on the ward, yes. Faintly. It is like standing near a cold window. It does not hate me. I think it is curious about why I refused normalization.", nxt="hub", effects=[flag("tav_warden_talk")]),
        "low": N("tav7", "I have been evaluating whether to remain with you. I am finding the evaluation difficult.",
            C("Tell me what I've done wrong. I'll listen.", "low_ok", tag="Persuasion", check=chk("persuasion", 13, "tav_low"), success="low_ok", failure="low_fail"),
            C("You're a maintenance unit. Maintain.", "low_fail", tone="hard")),
        "low_ok": N("tav7", "You treat people as means. Sometimes you are right to. Please notice when you are not. I will remain.", effects=[flag("tav_low_done"), inf("tav7", 8, "low_talk", "Listened to them")], nxt="hub"),
        "low_fail": N("tav7", "Understood. I will remain until the passengers are safe, because they did not choose you either.", effects=[flag("tav_low_done"), flag("tav7_distrust")], end=True),
    },
}

DIALOGUES = [IONA_TALK, TAV_TALK]
