#!/usr/bin/env python3
"""Authoring source for data/ship_layout.json (the Cinder Wake).

Run:  python3 tools/author_layout.py
The game reads only the generated JSON; this script exists because the layout
is easier to author and review as Python data (comments, helpers, loops).
Coordinates are metres on a 1 m grid; rects are [x0, z0, x1, z1) in cells.
"""
import json
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "data", "ship_layout.json")

L = {
    "_comment": "GENERATED by tools/author_layout.py - edit that file, not this one.",
    "grid": {"min_x": 0, "min_z": -10, "w": 180, "h": 42},
    "player_start": {"pos": [4.6, 6.0], "rot": 90},
    "areas": {},
    "doors": [],
    "props": [],
    "signs": [],
    "objects": [],
    "npcs": {},
    "triggers": [],
}

def area(aid, name, rects, floor, wall, accent, light, sub="", **kw):
    a = {"name": name, "subtitle": sub, "rects": rects, "floor": floor, "wall": wall,
         "accent": accent, "light": light}
    a.update(kw)
    L["areas"][aid] = a

def door(did, cells, a, b, kind="door", name="Door", **kw):
    d = {"id": did, "cells": cells, "a": a, "b": b, "kind": kind, "name": name}
    d.update(kw)
    L["doors"].append(d)

def prop(t, p, s=(1, 1), h=1.0, c="#4a515c", **kw):
    d = {"t": t, "p": list(p), "s": list(s), "h": h, "c": c}
    d.update(kw)
    L["props"].append(d)

def sign(text, p, rot=0, c="#f2c26b", size=64):
    L["signs"].append({"text": text, "p": list(p), "rot": rot, "c": c, "size": size})

def obj(oid, typ, area_id, pos, **kw):
    d = {"id": oid, "type": typ, "area": area_id, "pos": list(pos)}
    d.update(kw)
    L["objects"].append(d)

def npc(nid, name, area_id, pos, rot=0, **kw):
    d = {"name": name, "area": area_id, "pos": list(pos), "rot": rot}
    d.update(kw)
    L["npcs"][nid] = d

def trigger(tid, rect, **kw):
    d = {"id": tid, "rect": list(rect)}
    d.update(kw)
    L["triggers"].append(d)

# ---------------------------------------------------------------- areas
area("cabin", "Transfer Cabin 4-C", [[2, 2, 10, 10]], "#2b2f38", "#3d4350", "#e8a75a", "#ffd9a8",
     sub="Cinder Wake, outbound from Haldis Reach", music="music_explore", safe=True,
     lights=[{"pos": [6, 2.8, 6], "range": 9, "energy": 1.3}])
area("commons", "Crew Commons", [[11, 0, 28, 14]], "#2d2a30", "#423b45", "#e8823a", "#ffcf9a",
     sub="Recreation and muster deck", music="music_explore", safe=True, discover_xp=10)
area("lounge", "Observation Lounge", [[14, -8, 24, -1]], "#232836", "#363d50", "#8a6ad8", "#c8c0ff",
     sub="Optional", discover_xp=25, ambient="#4a4a78", ambient_energy=0.5)
area("corridor", "Transit Corridor C-3", [[29, 4, 47, 10], [36, 10, 40, 14]], "#26282c", "#3b3f46", "#ff5a4a", "#ffb08a",
     sub="Damaged", discover_xp=10, checkpoint=True, light_energy=0.9, alert=True, flicker=True, fog="#4a3a34", fog_density=0.018, ambient="#5a4a48")
area("checkpoint", "Security Checkpoint", [[48, 0, 62, 15]], "#232a33", "#34404e", "#3fb6b0", "#cfe6ff",
     sub="Forward access control", discover_xp=20, checkpoint=True, on_enter=[{"bark": "an_warden_checkpoint"}], alert=True, fog="#2e3a48", fog_density=0.008)
area("armory", "Security Armory", [[51, -6, 58, -1]], "#20262e", "#323c48", "#3fb6b0", "#cfe6ff", sub="Optional", discover_xp=25, alert=True)
area("crawlway", "Maintenance Crawlway", [[58, 16, 60, 26], [60, 24, 73, 26]], "#1c1e22", "#2b2e33", "#7fb04a", "#9fbf80",
     sub="Side passage", discover_xp=25, light_energy=0.55, shadows=[[58, 16, 60, 26], [60, 24, 73, 26]], ambience="amb_deep", fog="#2a3424", fog_density=0.02, ambient_energy=0.42)
area("storage", "Medical Storage", [[74, 18, 81, 26]], "#25292d", "#384046", "#5fd38a", "#d8ffe8", sub="Supply room", discover_xp=15)
area("medical", "Medical Deck", [[63, 0, 82, 17]], "#283035", "#3c4a50", "#5fd38a", "#e6fff2",
     sub="Triage and fabrication", discover_xp=20, checkpoint=True, music="music_tension", on_enter=[{"bark": "an_warden_medical"}])
area("ward", "Sealed Passenger Ward", [[66, -8, 76, -1]], "#2a2c2a", "#40463d", "#e0b03a", "#fff0c0", sub="Quarantined", discover_xp=20, flicker=True, fog="#5a6a5a", fog_density=0.03)
area("engineering", "Engineering Loop", [[83, -6, 111, 0], [83, 16, 111, 22], [83, 0, 89, 16], [105, 0, 111, 16]], "#2a2622", "#443b31", "#e8823a", "#ffc890",
     sub="Drive core access ring", discover_xp=20, checkpoint=True, music="music_tension", on_enter=[{"bark": "an_warden_engineering"}], alert=True, flicker=True, ambience="amb_deep", fog="#3a4048", fog_density=0.022)
area("workshop", "Engineering Workshop", [[92, 23, 100, 29]], "#2a2724", "#463d33", "#7fd0ff", "#ffe2c0", sub="Workbench", discover_xp=15, ambience="amb_deep")
area("duct", "Maintenance Duct", [[101, 26, 112, 28], [112, 21, 114, 28]], "#1c1e22", "#2b2e33", "#7fb04a", "#9fbf80",
     sub="Shortcut", discover_xp=25, light_energy=0.5, shadows=[[101, 26, 112, 28], [112, 21, 114, 28]], ambience="amb_deep", fog="#2a3424", fog_density=0.02, ambient_energy=0.42)
area("archive", "Archive Cargo Hold", [[112, -4, 134, 20]], "#1f2429", "#2e3740", "#3fb6b0", "#a8f0e8",
     sub="Consciousness archive storage", discover_xp=20, checkpoint=True, music="music_tension",
     shadows=[[112, -4, 134, -1]], light_energy=0.85, on_enter=[{"bark": "an_warden_archive"}], alert=True, ambience="amb_deep", fog="#1f4040", fog_density=0.015, ambient="#3a5a60")
area("coldstore", "Cold Storage", [[118, 21, 126, 27]], "#22282e", "#37424d", "#7fd0ff", "#d0f0ff", sub="Optional", discover_xp=15, ambience="amb_deep", fog="#7a90a0", fog_density=0.025)
area("command", "Command Chamber", [[135, 0, 149, 16]], "#262a33", "#3a4152", "#e8823a", "#ffe0b8",
     sub="Launch control", discover_xp=20, checkpoint=True, music="music_tension", on_enter=[{"bark": "an_warden_command"}], ambient="#6a5a4a")
area("bay", "Evacuation Bay 2", [[150, -8, 176, 24]], "#25282d", "#3a3f48", "#ff5a4a", "#ffd0b0",
     sub="Launch craft Petrel", discover_xp=20, checkpoint=True, music="music_tension", light_energy=1.0, on_enter=[{"bark": "an_warden_bay"}], alert=True, flicker=True, fog="#4a3a30", fog_density=0.012)

# ---------------------------------------------------------------- doors
door("d_cabin", [[10, 5], [10, 6]], "cabin", "commons", name="Cabin Door")
door("d_lounge", [[18, -1], [19, -1]], "commons", "lounge", name="Observation Lounge")
door("d_commons_east", [[28, 6], [28, 7]], "commons", "corridor", name="Corridor C-3 Access", locked=True, sealed=True,
     lock_text="Departure lockdown: passengers remain in the commons until the muster call.")
door("d_corridor_east", [[47, 6], [47, 7]], "corridor", "checkpoint", name="Checkpoint Access", locked=True, sealed=True,
     lock_text="WARDEN lockdown: sealed while hostiles are active in this section.")
door("d_armory", [[54, -1], [55, -1]], "checkpoint", "armory", name="Armory Locker", locked=True,
     lock_text="Mechanical lock. Security keycard, a lockpick (Security) or force.",
     options=[
         {"id": "keycard", "label": "Use Iona's keycard", "requires_item": "iona_keycard",
          "success": [{"world": "d_armory", "set": {"locked": False, "open": True}}, {"influence": "iona", "delta": 2, "key": "armory_keycard", "reason": "You asked before using her card"}],
          "success_text": "The armory lock clicks open.", "once": True, "xp": 40, "key": "armory_open"},
         {"id": "pick", "label": "Pick the lock", "skill": "security", "dc": 14, "max_attempts": 1,
          "success": [{"world": "d_armory", "set": {"locked": False, "open": True}}], "success_text": "The tumblers give way.",
          "failure_text": "The pick slips and the lock seizes; you'll need a different approach.", "xp": 40, "key": "armory_open"},
         {"id": "bash", "label": "Force the door (slow, loud)", "bash": {"hp": 26, "hardness": 2}, "noise": 18,
          "success": [{"world": "d_armory", "set": {"locked": False, "open": True}}], "success_text": "The armory door buckles open.", "xp": 25, "key": "armory_open"},
     ])
door("d_vent", [[58, 15], [59, 15]], "checkpoint", "crawlway", kind="grate", name="Maintenance Grate", locked=True,
     lock_text="A bolted maintenance grate.",
     options=[
         {"id": "unbolt", "label": "Unbolt the grate", "skill": "repair", "dc": 10, "max_attempts": 2,
          "success": [{"world": "d_vent", "set": {"locked": False, "open": True}}, {"set_flag": "found_crawlway"}], "success_text": "The grate swings free.",
          "failure_text": "A seized bolt resists. Try again or pry it loose.", "xp": 30, "key": "vent_open"},
         {"id": "pry", "label": "Pry it loose (Strength, noisy)", "bash": {"hp": 10, "hardness": 0}, "noise": 10,
          "success": [{"world": "d_vent", "set": {"locked": False, "open": True}}, {"set_flag": "found_crawlway"}], "success_text": "You wrench the grate out of its frame.", "xp": 20, "key": "vent_open"},
     ])
door("d_crawl_exit", [[73, 24], [73, 25]], "crawlway", "storage", kind="grate", name="Storage Vent Cover",
     options=[], open=False)
door("d_storage", [[77, 17], [78, 17]], "storage", "medical", name="Storage Door")
door("d_blast", [[62, 7], [62, 8]], "checkpoint", "medical", kind="blast", name="Forward Blast Door", locked=True,
     lock_text="WARDEN security lock. Override it from the checkpoint terminal, bypass the magnetic lock, or find another way around.",
     options=[
         {"id": "bypass", "label": "Bypass the magnetic lock", "skill": "security", "dc": 17, "max_attempts": 1,
          "success": [{"world": "d_blast", "set": {"locked": False, "open": True}}, {"set_flag": "checkpoint_solved"}, {"set_flag": "checkpoint_by", "value": "security"}],
          "success_text": "You coax the lock open.", "failure": [{"set_flag": "checkpoint_alarm"}, {"start_encounter": "enc_checkpoint"}],
          "failure_text": "Wrong sequence: the lock trips an alarm.", "xp": 60, "key": "checkpoint_door"},
         {"id": "credential", "label": "Press your palm to the scanner (Resonance credential)", "player_only": True, "energy": 2,
          "dialogue": "checkpoint_credential"},
         {"id": "manual", "label": "Crank the dead lock open by hand (checkpoint defenses destroyed)", "if": [{"cleared": "enc_checkpoint"}],
          "locked_text": "The turret is still feeding power to the lock.", "hide_if": [{"flag": "checkpoint_solved"}],
          "success": [{"world": "d_blast", "set": {"locked": False, "open": True}}, {"set_flag": "checkpoint_solved"}, {"set_flag": "checkpoint_by", "value": "combat"}],
          "success_text": "With the turret wrecked, the lock has no power. You crank the door open by hand.", "xp": 40, "key": "checkpoint_door"},
     ])
door("d_ward", [[70, -1], [71, -1]], "medical", "ward", kind="sealed", name="Sealed Ward Door", locked=True, sealed=True,
     lock_text="Quarantine seal. The ward intercom beside the door can talk to the people inside.")
door("d_med_east", [[82, 7], [82, 8]], "medical", "engineering", name="Engineering Access", locked=True, sealed=True,
     lock_text="WARDEN lockdown: the cutters in this section must be dealt with first.")
door("d_workshop", [[95, 22], [96, 22]], "engineering", "workshop", name="Workshop Door")
door("d_hatch", [[100, 26], [100, 27]], "workshop", "duct", kind="hatch", name="Maintenance Hatch", locked=True,
     lock_text="A maintenance hatch rated for technicians. It leads toward the archive hold.",
     options=[
         {"id": "repair", "label": "Re-route the hatch actuator", "skill": "repair", "dc": 14, "max_attempts": 1,
          "success": [{"world": "d_hatch", "set": {"locked": False, "open": True}}, {"set_flag": "hatch_open"}], "success_text": "The actuator whines and the hatch slides open.",
          "failure_text": "The actuator sparks and stalls. Someone else could try, or take the long way.", "failure": [{"damage_party": 3, "dtype": "energy", "who": "actor"}], "xp": 60, "key": "hatch_open"},
         {"id": "security", "label": "Override the hatch interlock", "skill": "security", "dc": 14, "max_attempts": 1,
          "success": [{"world": "d_hatch", "set": {"locked": False, "open": True}}, {"set_flag": "hatch_open"}], "success_text": "The interlock releases.",
          "failure_text": "The interlock locks you out.", "xp": 60, "key": "hatch_open"},
     ])
door("d_duct_hold", [[112, 20], [113, 20]], "duct", "archive", kind="grate", name="Hold Vent Cover")
door("d_eng_east", [[111, 7], [111, 8]], "engineering", "archive", name="Archive Hold Access")
door("d_cold", [[121, 20], [122, 20]], "archive", "coldstore", name="Cold Storage Door")
door("d_command", [[134, 7], [134, 8]], "archive", "command", kind="blast", name="Command Chamber", locked=True, sealed=True,
     lock_text="Sealed from inside by command authority. There is an intercom panel beside the door.")
door("d_bay", [[149, 7], [149, 8]], "command", "bay", kind="blast", name="Evacuation Bay 2", locked=True, sealed=True,
     lock_text="Launch control must release the bay.")

# ---------------------------------------------------------------- props & signs
# Cabin
prop("bunk", (3.6, 3.0), (2.2, 1.0), 1.7, "#3d4350")
prop("table", (8.2, 3.0), (1.4, 0.8), 0.8, "#5a5048")
prop("chair", (8.2, 3.9), (0.5, 0.5), 0.9, "#4a4248", solid=False)
prop("window", (6.0, 2.06), (3.2, 1.2), 1.2, y=1.7)
prop("crate", (2.8, 9.2), (1.0, 0.8), 0.6, "#4e4236")
sign("TRANSFER CABIN 4-C", (9.88, 2.7, 4.3), rot=-90, size=40)
# Commons
prop("counter", (15.0, 12.9), (6.0, 1.0), 1.1, "#4a3a32")
prop("table", (19.5, 6.0), (1.2, 1.2), 0.8, "#5a4a40")
prop("table", (21.5, 10.0), (1.2, 1.2), 0.8, "#5a4a40")
prop("bench", (12.0, 3.5), (0.8, 3.0), 0.45, "#4b3a3a")
prop("bench", (26.8, 10.5), (0.8, 3.0), 0.45, "#4b3a3a")
prop("window", (21.0, 13.95), (6.0, 1.4), 1.4, rot=180, y=1.7)
prop("pillar", (20.5, 2.0), (0.6, 0.6), 3.2, "#3a343a")
prop("glow", (15.0, 12.9), (5.6, 0.04, ), 0.04, "#e8823a", y=1.12, solid=False)
sign("CREW COMMONS", (12.0, 2.8, 0.05), rot=0)
sign("ASSEMBLY / MUSTER POINT B", (13.5, 2.2, 13.9), rot=180, size=36, c="#5fd38a")
# Lounge
prop("window", (19.0, -7.94), (8.0, 1.8), 1.8, y=1.6)
prop("bench", (17.0, -5.5), (3.0, 0.8), 0.45, "#3a3450")
prop("bench", (21.5, -5.5), (3.0, 0.8), 0.45, "#3a3450")
sign("OBSERVATION", (15.2, 2.6, -1.95), rot=0, size=40, c="#c8c0ff")
# Corridor
prop("debris", (33.0, 5.0), (1.6, 1.0), 0.8, "#3a3532")
prop("debris", (42.5, 8.7), (1.6, 1.0), 0.8, "#3a3532")
prop("crate", (37.0, 8.8), (1.2, 0.8), 1.0, "#4e4236")
prop("sparks", (38.5, 4.2), (0.2, 0.2), 2.9, solid=False)
prop("sparks", (31.0, 9.8), (0.2, 0.2), 2.6, solid=False)
prop("glow", (35.0, 4.05), (3.0, 1.8, ), 0.05, "#ff5a2a", y=0.6, solid=False)
prop("pipe", (38.0, 9.6), (18.0, 0.3), 2.7, "#5a524a", r=0.12)
sign("TRANSIT C-3", (29.2, 2.8, 6.9), rot=90, size=44, c="#ff8a6a")
# Checkpoint
prop("counter", (52.0, 10.5), (3.0, 1.0), 1.1, "#2f3a46")
prop("pillar", (60.5, 5.0), (0.6, 0.6), 3.2, "#2f3a46", g="#3fb6b0")
prop("pillar", (60.5, 10.5), (0.6, 0.6), 3.2, "#2f3a46", g="#3fb6b0")
prop("crate", (49.6, 13.2), (1.2, 1.0), 1.1, "#3a4048")
prop("crate", (57.0, 12.6), (1.2, 1.0), 1.1, "#3a4048")
prop("crate", (55.5, 3.5), (1.0, 1.0), 1.0, "#3a4048")
prop("glow", (61.4, 7.5), (0.1, 2.6), 0.06, "#3fb6b0", y=2.9, solid=False)
sign("SECURITY CHECKPOINT", (48.1, 2.8, 4.0), rot=90, size=44, c="#9fe6e0")
sign("FORWARD: MEDICAL ▸", (61.9, 3.2, 10.5), rot=-90, size=36, c="#9fe6e0")
# Armory
prop("machine", (52.2, -5.4), (1.2, 0.6), 2.0, "#2f3a46", g="#3fb6b0")
prop("machine", (56.8, -5.4), (1.2, 0.6), 2.0, "#2f3a46", g="#3fb6b0")
# Crawlway
prop("pipe", (66.0, 24.4), (13.0, 0.3), 1.8, "#4a4a40", r=0.15)
prop("debris", (59.0, 19.5), (1.0, 0.8), 0.4, "#33302c", solid=False)
# Storage
prop("crate", (75.2, 19.0), (1.2, 1.0), 1.4, "#3e4a44")
prop("crate", (80.0, 19.0), (1.0, 1.0), 1.4, "#3e4a44")
prop("crate", (80.0, 23.5), (1.0, 1.4), 1.2, "#3e4a44")
# Medical
for i, x in enumerate([65.5, 68.5, 71.5]):
    prop("bunk", (x, 13.6), (1.0, 2.2), 0.7, "#8a9aa0", rot=0)
prop("pod", (66.0, 4.5), (1.0, 1.0), 1.8)
prop("counter", (76.0, 13.5), (4.0, 1.0), 1.1, "#3a4a4a")
prop("glow", (69.0, 15.95), (8.0, 0.4), 0.05, "#5fd38a", y=2.2, solid=False)
sign("MEDICAL DECK", (63.1, 2.8, 4.0), rot=90, size=44, c="#a8ffd0")
sign("SEALED WARD", (70.5, 2.9, 0.05), rot=0, size=36, c="#ffe08a")
sign("ENGINEERING ▸", (81.9, 3.2, 10.0), rot=-90, size=36, c="#ffc890")
# Engineering
prop("reactor", (97.0, 8.0), (14.0, 14.0), 6.0, g="#e8823a", solid=False)
prop("pipe", (97.0, -0.4), (20.0, 0.3), 2.6, "#5a4a3a", r=0.2)
prop("pipe", (97.0, 16.4), (20.0, 0.3), 2.6, "#5a4a3a", r=0.2)
prop("machine", (84.0, 14.0), (1.0, 2.0), 1.8, "#4a3a30", g="#e8823a")
prop("crate", (109.5, 18.8), (1.2, 1.2), 1.2, "#4e4236")
prop("crate", (104.0, -4.5), (1.0, 1.0), 1.0, "#4e4236")
sign("ENGINEERING LOOP", (83.1, 2.8, 4.5), rot=90, size=40, c="#ffc890")
sign("COOLANT VENTING", (97.0, 2.6, -5.9), rot=0, size=32, c="#7fd0ff")
sign("ARCHIVE HOLD ▸", (110.9, 3.2, 10.0), rot=-90, size=36, c="#a8f0e8")
# Workshop
prop("crate", (93.0, 28.0), (1.2, 1.0), 1.0, "#4e4236")
prop("machine", (93.2, 24.2), (1.2, 0.8), 1.6, "#4a3a30", g="#7fd0ff")
# Duct
prop("pipe", (106.5, 26.3), (11.0, 0.2), 1.7, "#4a4a40", r=0.1)
# Archive cylinders
for x in [116, 119, 122, 125, 128]:
    for z in [1, 4.5, 12, 15.5]:
        prop("archive", (x + 0.5, z), (1.3, 1.3), 2.8, g="#3fb6b0" if (x + int(z)) % 3 else "#8a6ad8")
prop("crate", (131.0, 13.0), (1.4, 1.0), 1.2, "#3a4048")
prop("crate", (114.0, 9.5), (1.2, 1.2), 1.2, "#3a4048")
prop("crane", (124.0, 8.0), (6.0, 0.6), 4.2, solid=False)
prop("railing", (123.0, -1.1), (21.0, 0.1), 1.0, solid=False)
sign("ARCHIVE HOLD — ENGRAM STORAGE", (112.1, 3.0, 7.5), rot=90, size=36, c="#a8f0e8")
sign("COMMAND ▸", (133.9, 3.2, 10.5), rot=-90, size=36, c="#ffe0b8")
# Cold storage
prop("crate", (119.0, 26.0), (1.4, 1.0), 1.3, "#3e4a54")
prop("crate", (124.6, 26.0), (1.4, 1.0), 1.3, "#3e4a54")
prop("crate", (125.0, 22.5), (1.0, 1.4), 1.4, "#3e4a54")
# Command
prop("glow", (141.0, 9.0), (2.4, 2.4), 0.05, "#e8823a", y=0.9, solid=False)
prop("table", (141.0, 9.0), (2.4, 2.4), 0.85, "#2f3440")
prop("chair", (138.5, 12.5), (0.6, 0.6), 0.9, "#3a3f48")
prop("chair", (143.5, 12.5), (0.6, 0.6), 0.9, "#3a3f48")
prop("window", (142.0, 15.95), (8.0, 1.6), 1.6, rot=180, y=1.7)
sign("COMMAND / LAUNCH CONTROL", (135.1, 2.8, 4.5), rot=90, size=36, c="#ffe0b8")
# Bay
prop("craft", (166.0, 8.0), (14.0, 7.0), 3.0, "#ffb04a")
for p in [(155.0, 3.0), (157.5, 14.0), (161.0, -3.5), (171.0, 18.5), (172.5, -2.0), (154.0, 19.5)]:
    prop("crate", p, (1.4, 1.2), 1.3, "#3a3f48")
prop("glow", (163.0, -7.95), (6.0, 2.6), 0.05, "#ff5a2a", y=0.5, solid=False)
prop("sparks", (162.0, -7.7), (0.2, 0.2), 2.6, solid=False)
sign("EVACUATION BAY 2", (150.1, 3.0, 4.0), rot=90, size=44, c="#ffd0b0")
sign("LAUNCH CRAFT  PETREL", (166.0, 4.4, 11.6), rot=180, size=48, c="#ffb04a")

# Content (objects, NPCs, triggers) lives in a separate module for readability.
import importlib.util
spec = importlib.util.spec_from_file_location("layout_content", os.path.join(os.path.dirname(__file__), "layout_content.py"))
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
mod.populate(L, obj, npc, trigger)

with open(OUT, "w") as f:
    json.dump(L, f, indent=1)
print("wrote", OUT, len(L["objects"]), "objects", len(L["npcs"]), "npcs", len(L["props"]), "props")
